Local Kubeflow orchestrator uses active context
zenml-io/zenml pull request #1066
Opened 2022-11-13 23:15 UTC by safoinme

## Describe changes
I think the kubernetes_context should return the active stack if one is set, only if it's not set to return to the k3d k8s cluster.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [X] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-11-14 09:12 UTC, stefannica requested changes

2022-11-16 16:11 UTC, fa9r reviewed
Overall this looks good to me.

One thing I was wondering though is whether you could further disentangle the k3d code from the local Kubeflow orchestrator, i.e., move all k3d functionality to some separate module that the local Kubeflow orchestrator imports.

The reason I am asking is that this might then directly enable local Kubernetes as well for which we have a separate open ticket (ENG-983), so you could potentially implement two big features at once with this PR :D

2022-11-17 08:21 UTC, stefannica requested changes
Without looking at the code changes in depth, I imagine this change also requires a lot of updates to our documentation and examples, but I didn't see any.

2022-11-17 10:15 UTC, fa9r approved these changes
Code looks good to me.

It seems k3d and the local kubeflow are still tighly coupled, but I guess we can merge this PR and then do those other changes later without release pressure. Perhaps trying to implement a local k3d Kubernetes orchestrator while refactoring the k3d code out might also be helpful since you will directly notice which code parts need to be duplicated and should therefore be extracted/abstracted.

@stefannica regarding docs I think we decided that we do not need separate examples/docs pages for the local k3d orchestrators for now. However, you are right in that there might be places in the docs or examples that will be outdated after this PR. @safoinme did you go through our content once and check that?

2022-11-17 10:22 UTC, fa9r commented
Also, one of the kfp unit tests it failing

2022-11-17 10:22 UTC, schustmi commented on src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
> +        )
```suggestion
        return self.config.kubernetes_context
```

2022-11-17 10:25 UTC, schustmi commented
I'm guessing this also breaks all existing stacks with local kubeflow orchestrators because of the new flavor name?
In which case this needs also some comments on how to migrate these

2022-11-17 10:33 UTC, schustmi requested changes

2022-11-17 10:33 UTC, schustmi commented on src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
>          skip_ui_daemon_provisioning: If `True`, provisioning the KFP UI daemon
This is not currently doing anything for the remote orchestrator, should we move it or re-introduce this functionality?

2022-12-19 23:05 UTC, closed without merging