Docs regarding roles and permissions (#1081)
zenml-io/zenml pull request #1087
Opened 2022-11-21 16:35 UTC by AlexejPenner

* Docs regarding roles and permissions

* Apply suggestions from code review

Co-authored-by: Felix Altenberger <felix@zenml.io>

* Added roles and permissions to the toc

Co-authored-by: Felix Altenberger <felix@zenml.io>

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-11-21 16:41 UTC, htahir1 requested changes
left some comments :-)

2022-11-21 16:41 UTC, htahir1 commented on docs/book/starter-guide/collaborate/roles-and-permissions.md
> +future. Feel free to let us know on Slack or through our Roadmap if this is
Please link these (Slack) and (Roadmap)

2022-11-21 16:41 UTC, htahir1 commented on docs/book/starter-guide/collaborate/roles-and-permissions.md
> +* Permissions and roles only become relevant if you are running through a
Link to deployed ZenML Server?

2022-11-21 16:41 UTC, htahir1 commented on docs/book/starter-guide/collaborate/roles-and-permissions.md
> +**guest**: The guest role lets users change their own user data and grants
read access or also 'me' access?

2022-11-21 20:52 UTC, AlexejPenner commented
@htahir1 thanks for your comments, however this is a cherry picked commit on develop as a backport into the release branch. Wouldn't it make sense to make these changes on develop and create a separate backport?

2022-11-22 11:44 UTC, fa9r commented
@AlexejPenner you could also make the changes on develop and then backport both changes at the same time by cherry picking twice ;)

2022-11-22 11:44 UTC, fa9r commented
but yes, we definitely need the changes on dev first

2022-11-22 11:47 UTC, fa9r reviewed
See above, would recommend to first make the changes @htahir1 requested in a separate mini PR to develop, then cherry pick that PR into this one as well so you can backport both

2022-11-22 13:47 UTC, htahir1 approved these changes
Thats great!!

2022-11-22 13:47 UTC, merged