Remove Pyarrow dependency
zenml-io/zenml pull request #1109
Opened 2022-11-25 09:58 UTC by safoinme

## Describe changes
Remove Pyarrow while updating the NumPy materialize.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-11-25 10:27 UTC, schustmi requested changes
The only problem I see here is backwards compatability. If we now (due to caching, or a user explicitly requesting) try load an artifact that was stored with an older version of ZenML, the loading fails. Can we maybe include some logic like this:

```python
if fileio.exists(new_file):
    # use the logic you now implemented
elif fileio.exists(old_files):
    try:
        import pyarrow
        # use old logic here
    except ImportError:
        # error message that tells them to install pyarrow to load legacy artifacts   
```

2022-11-26 19:36 UTC, fa9r approved these changes
The main change here is that we now use `.npy` format instead of `.parquet` when saving numpy arrays. Generally, this makes sense. 

However, if you have a big dataset, you might prefer to use `.parquet` over `.npy`, so it would be cool if we still had the old option available as well. This reminded me again of how awkward our materializer installation is right now: Since we don't want the added dependency, we would need to add the numpy parquet materializer as a separate integration, which also feels really weird.

@schustmi haven't we already discussed this over lunch the other day? Do you still remember what we came up with back then? 😅

Now, getting back on topic, the PR achieves what it should and the code looks good so 👍 from my side :)

2022-11-26 21:41 UTC, safoinme commented on src/zenml/materializers/numpy_materializer.py
> +                    "You can do so by running `pip install pyarrow`.",
All your suggestions are welcomed and important! thank you so much for always leaving reviews.

2022-11-26 22:16 UTC, safoinme commented
@fa9r Thank you for the clarification on the new implementation and removal of `pyarrow`. I have a question, however, why is `parquet` considered better or preferable over `npy` or maybe `npz` which is the more compressed format of `npy` when it comes to big datasets?

2022-11-27 18:45 UTC, fa9r commented
@safoinme You're right, `.npy` seems to be even more efficient than parquet for storing numpy arrays 👍

2022-11-27 18:46 UTC, fa9r commented
In that case, ignore my comment from above, perhaps we will have this discussion in the future again if we ever choose to redesign the pandas materializer :D

2022-11-27 20:39 UTC, safoinme commented
@fa9r I think that time has come hahaha! `pandas materialize` requires `pyarrow` which must be changed to `pickle`. while `parquet` is actually better performing in read and write when it's numerical data, pickle is better in categorical data pickle is actually better. according to this: [The Best Format to Save Pandas Data](https://towardsdatascience.com/the-best-format-to-save-pandas-data-414dca023e0d)

2022-11-28 08:26 UTC, schustmi requested changes
The numpy materializer looks great now!

I'm a little concerned by the pandas materializer (we don't usually use `pickle` as it can become problematic when loading the stored pickle file from a different OS/python version). Is there any other native way to store these instead of using pickle?

2022-11-28 09:28 UTC, safoinme commented
@schustmi unfortunately alternative ways are either not native or not really performant in comparison to `pickle` or `parquet` however regarding the compatibility thing I don't think it's actually an os issue but more like a python issue which mainly occurs due to not specifying the protocol version which means newer python version (3.9>) will use the latest protocol `5` while the old one will use `4`. if we force this to 4  which is supported n all current python versions zenml support this may prevent compatibility issues.

2022-11-29 07:21 UTC, fa9r requested changes
@safoinme I'm not a big fan of pickle either because of the compatibility issues @schustmi mentioned. Perhaps we should have a short meeting today to discuss the pros/cons of the various formats pandas supports.

2022-11-29 12:04 UTC, fa9r commented
Ah CI is already passing? Thought it would at least complain because `is_dataframe_or_series()` has no docstring. Nevermind, in that case looks all good from my side 🚀

2022-11-29 12:29 UTC, safoinme commented on src/zenml/materializers/pandas_materializer.py
> +                    "`fastparquet`for reading, You can install `pyarrow` & "
Apparently, it's optional `pyarrow` can be enough but `fastparquet` does exactly the same work as `pyarrow` there are big debates on StackOverflow about which one is better and produces fewer issues. so we will just stick with pyarrow for now I think

2022-11-29 14:30 UTC, AlexejPenner approved these changes
:seal:

2022-11-29 14:41 UTC, merged