Prevent running with local ZenStore and remote code execution
zenml-io/zenml pull request #1134
Opened 2022-12-05 10:52 UTC by schustmi

## Describe changes
This PR adds an error if trying to run with a remote orchestrator or step operator in combination with a local ZenStore.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-12-05 15:44 UTC, htahir1 requested changes
Small PR

2022-12-05 15:44 UTC, htahir1 commented on src/zenml/stack/stack.py
> +                "more information on how to deploy ZenML."
Please feel free to reformat in your IDE. My suggestion is more on wording.

```suggestion
                "Stacks with remote components such as remote orchestrators "
                "and step operators require a remote "
                "ZenML server. To run a pipeline with this stack you need to "
                "connect to a remote ZenML server first. Check out "
                "https://docs.zenml.io/getting-started/deploying-zenml for "
                "more information on how to deploy ZenML."
```

2022-12-05 15:44 UTC, htahir1 commented on src/zenml/stack/stack.py
> +        return self.orchestrator.config.is_remote or (
In what other cases do you think in the future we can throw this error?

2022-12-05 20:20 UTC, AlexejPenner approved these changes
🦭 of approval - pending Passing CI

2022-12-05 22:53 UTC, safoinme approved these changes
LGTM

2022-12-06 08:22 UTC, htahir1 approved these changes

2022-12-06 08:52 UTC, merged