Move pandas and numpy as integrations
zenml-io/zenml pull request #1143
Opened 2022-12-05 17:07 UTC by htahir1

## Describe changes
I have attempted to refactor numpy and pandas as integrations rather than explicitly installing them/

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-12-05 20:04 UTC, schustmi requested changes
One other thing that is missing here is adding `numpy/pandas` to the `required_integrations` for all examples/blog posts that require them

2022-12-05 20:04 UTC, schustmi commented on src/zenml/integrations/numpy/__init__.py
> +#  Copyright (c) ZenML GmbH 2021. All Rights Reserved.
```suggestion
#  Copyright (c) ZenML GmbH 2022. All Rights Reserved.
```

:P

2022-12-05 20:04 UTC, schustmi commented on src/zenml/integrations/numpy/__init__.py
> +    """Definition of NUMPY integration for ZenML."""
```suggestion
    """Definition of NumPy integration for ZenML."""
```

2022-12-07 14:30 UTC, fa9r requested changes
Implementation so far looks good.

One thing that is still missing is to adjust the requirements of all other integrations that depend on numpy or pandas being installed. E.g., almost all data validator, feature store, and visualizer integrations do `import pandas as pd`, and some of the model deployers do `import numpy as np`, which might or might not work depending on whether the respective tool itself has numpy/pandas as a requirement. To be save, I would just add numpy/pandas as a requirement in the respective integration init.

2022-12-14 09:51 UTC, htahir1 commented
Closing because of internal discussions that we keep numpy and pandas as core dependencies for now

2022-12-15 18:06 UTC, closed without merging