Add support for deploying custom stack recipes using the ZenML CLI
zenml-io/zenml pull request #1188
Opened 2022-12-21 07:08 UTC by wjayesh

## Describe changes
I implemented a `--skip-pull` flag that can be used to deploy a local stack recipe.

## Usage
If you have a recipe under the folder name, `my-custom-recipe` in the current directory, you can deploy it using this command:
```
zenml stack recipe deploy my-custom-recipe -p . --skip-pull
```
 where the `-p` flag is used to select the path to the directory that hosts the recipe.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-12-22 08:20 UTC, htahir1 requested changes

2022-12-22 08:20 UTC, htahir1 commented on src/zenml/cli/stack_recipes.py
> +                    "If you want to deploy a custom stack recipe available "
Can we add something here about specifying the path of where the custom stack recipe is ?

2022-12-22 08:20 UTC, htahir1 commented on src/zenml/cli/stack_recipes.py
> +    "if you have a local copy of your recipe already.",
again mention the path here. how can we specify the path?

2022-12-22 08:20 UTC, htahir1 commented on src/zenml/cli/stack_recipes.py
> +                    "If you want to deploy a custom stack recipe available "
On a side note, the `-p` help message needs impormvents: It now says "Relative path at which you want to install the stack recipe(s)". It should be "Relative path at which local stack recipe(s) should exist"

2022-12-23 10:38 UTC, htahir1 approved these changes
Ok I hope this is tested! :D

2022-12-23 10:57 UTC, wjayesh commented
yes, I have done some manual testing with a custom recipe and that worked fine.

2022-12-23 10:57 UTC, merged