Tests for `network_utils`
zenml-io/zenml pull request #1201
Opened 2022-12-22 15:21 UTC by strickvl

Added tests for the `network_utils` code.

Wasn't fully sure of the best way to test this kind of network calls / scans, so happy to rework following any feedback that might come my way.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-12-22 15:59 UTC, fa9r approved these changes
Just a few minor suggestions, overall LGTM!

2022-12-22 15:59 UTC, fa9r commented on tests/unit/utils/test_networking_utils.py
> +    assert isinstance(networking_utils.port_available(open_port), bool)
```suggestion
    networking_utils.port_available(open_port) is True
```

2022-12-22 15:59 UTC, fa9r commented on tests/unit/utils/test_networking_utils.py
> +        assert networking_utils.port_is_open("127.0.0.1", 8000) is False
I think `sock.bind` could fail for 8000 if that port is already occupied on my local machine

```suggestion
        sock.bind(("127.0.0.1", open_port))
        assert networking_utils.port_is_open("127.0.0.1", open_port) is False
```

2022-12-22 15:59 UTC, fa9r commented on tests/unit/utils/test_networking_utils.py
> +    )
```suggestion
    assert networking_utils.port_is_open("127.0.0.1", open_port) is True
```

2023-01-11 08:50 UTC, stefannica requested changes
One suggestion, looks great otherwise

2023-01-11 08:50 UTC, stefannica commented on tests/unit/utils/test_networking_utils.py
> +    networking_utils.port_available(open_port) is True
```suggestion
    assert networking_utils.port_available(open_port) is True
```

... is probably what you meant.

2023-01-11 14:02 UTC, stefannica approved these changes

2023-01-12 15:30 UTC, merged