Test `filesync_model` utils
zenml-io/zenml pull request #1230
Opened 2023-01-12 17:02 UTC by strickvl

Tests for the `filesync_model` utility class.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-01-12 19:03 UTC, fa9r requested changes
Some basic docstrings to explain what the tests are doing would be nice, otherwise looks good.

2023-01-12 20:43 UTC, fa9r approved these changes
Nice :)

2023-01-13 10:07 UTC, schustmi approved these changes

2023-01-13 10:07 UTC, schustmi commented on tests/unit/utils/test_filesync_model.py
> +    assert model.cat_name == "aria"
```suggestion
    assert model.cat_name == SOFTCAT1
```
?

2023-01-13 10:13 UTC, merged