Fixed startswith and endswith
zenml-io/zenml pull request #1278
Opened 2023-01-31 16:42 UTC by AlexejPenner

## Describe changes
In the conversion from SqlAlchemy to SQL the additional `%` were interpreted wrongly

name=contains:<str> -> `workspace.name LIKE  `%` || <str> || '%'`
name=startswith:<str> -> `workspace.name LIKE  <str> || '%'`
name=endswith:<str> -> `workspace.name LIKE  `%` || <str>

Having these extra `%` converted every command into a contains command.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-01-31 16:54 UTC, fa9r approved these changes
fix makes sense, approving with the assumption that you tested this manually

2023-01-31 16:54 UTC, fa9r commented on src/zenml/client.py
> +            stack_id: The  id of the stack to filter by.
🧐

```suggestion
            stack_id: The id of the stack to filter by.
```

2023-02-01 10:41 UTC, schustmi requested changes

2023-02-01 10:41 UTC, schustmi commented on src/zenml/client.py
>              user_id: The  id of the user to filter by.
```suggestion
            user_id: The id of the user to filter by.
```

2023-02-01 13:22 UTC, merged