Update evidently to include reports and tests
zenml-io/zenml pull request #1283
Opened 2023-02-02 13:58 UTC by wjayesh

## Describe changes
I updated our evidently integration to v0.2.2 which replaces Profiles and Dashboard with the Report object and introduces the concept of TestSuites.

### Data Profiling
Profiling is now achieved through the use of the Report object.
It takes in a list of metrics to evaluate the data on and can be viewed as a JSON and an HTML object. This functionality is now reflected in the `evidently_report_step` which replaces the `evidently_profile_step` we had earlier.

### Data Validation
There's also a new step now that performs data validation using Evidently's TestSuites.
The `evidently_test_step` has a similar API to the report step but deals with generating test reports that indicate if the metrics pass/fail with respect to some threshold.

## Work in progress

### Example
The example in its current form is only good for validating that the report and test additions function. I want to update it to make more sense and also add in some of the newer features like text profiling. Use the example only to get an idea of what the new flow will look like.

### Documentation
No documentation on the newer features exist and will be added soon.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-02-02 14:00 UTC, wjayesh commented on src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
> +        # if metric contains preset in name, return an object of the class of same name from metric_preset
I need advice here. Is this the right way to handle loading the classes from the string values? Earlier, we used a map to link the strings and their respective classes.

2023-02-02 14:00 UTC, wjayesh commented on src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
>      """
I need advice here. Is this the right way to handle loading the classes from the string values? Earlier, we used a map to link the strings and their respective classes.

2023-02-02 14:51 UTC, htahir1 reviewed
I have not checked this thoroughly but my big question is what happens to all current usages of evidently with ZenML? How are you handling deprecation here?

2023-02-02 14:51 UTC, htahir1 commented on src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
> +    # metric_mapping = {
I think it makes sense to me, and is better than hard-coded list

2023-02-03 05:01 UTC, wjayesh commented
@htahir1 I have added support for the existing `evidently_profile_step` so folks using that should not be affected.

2023-02-09 12:13 UTC, htahir1 requested changes
Please also update quickstart and other examples in PR's in ZenML projects and ZenBytes as this is one of the most widely used integratins we have to careful

2023-03-02 09:39 UTC, merged