Change zenml init --template to optionally prompt and track email
zenml-io/zenml pull request #1298
Opened 2023-02-07 16:22 UTC by stefannica

## Describe changes
Add a `--starter` flag to `zenml init` to generate the starter template without prompting for user input (use default param values).
Both `zenml init --starter` and `zenml init --template` ask for a user email the first time they are used, which is tracked.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-02-07 16:43 UTC, strickvl requested changes
Core functionality is fine, but when you actually do this it looks a bit weird in the CLI:

![ScreenShot 2023-02-07 at 17 41 36](https://user-images.githubusercontent.com/3348134/217307959-2579c36a-c217-4cab-b8c2-fc7f35d2bbab.png)

Esp the 'Next you will be prompted..." line. Either could do with being broken up by some line breaks, or a header, or something to separate it from the privacy statement above.

2023-02-07 16:43 UTC, strickvl commented on src/zenml/cli/base.py
> +            zenml_go_welcome_message,
```suggestion
            zenml_cli_privacy_message,
            zenml_cli_welcome_message,
```

Probably wants changing? (and in `text_utils.py` file)

2023-02-07 17:21 UTC, stefannica commented
Better, I hope: 

![Screenshot from 2023-02-07 18-20-44](https://user-images.githubusercontent.com/3963946/217317640-12db0ec4-6d6a-4b8d-a577-1d6d239b9dd5.png)

2023-02-08 09:04 UTC, strickvl approved these changes
Looks good now!

2023-02-08 15:13 UTC, merged