Add warning when attempting server connection without user permissions
zenml-io/zenml pull request #1314
Opened 2023-02-09 17:13 UTC by strickvl

Added a warning that catches the `IllegalOperationError` that we previously handed to the user without context/explanation.

Following discussion with @AlexejPenner, we agreed that there aren't really any scenarios we could imagine where a user might want to be logged into a ZenML server without any permissions attached to their role.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-02-10 09:27 UTC, schustmi commented
Is this something that we can add a test for or is that unreasonably complicated?

2023-02-10 09:35 UTC, AlexejPenner commented
> Is this something that we can add a test for or is that unreasonably complicated?

I don't think the test harness currently allows for attempting to connect to a new deployed zenml server. It also feels like unproportional effort to create this scenario for a niche exception like this one.

2023-02-10 09:46 UTC, schustmi commented
What I had in mind, but might not be possible:
When the test are running with a rest zen server, create a new user without role. Then run CLI `connect` command to connect to that already connected server (or disconnect first if necessary) which should trigger this? But I now realize we only log a warning which isn't testable anyway I guess

2023-02-10 09:54 UTC, strickvl commented
> What I had in mind, but might not be possible: When the test are running with a rest zen server, create a new user without role. Then run CLI `connect` command to connect to that already connected server (or disconnect first if necessary) which should trigger this? But I now realize we only log a warning which isn't testable anyway I guess

Technically we could test that the `IllegalOperationError` doesn't get raised...

2023-02-10 09:57 UTC, schustmi commented
Probably not worth it though, maybe if it works after 5 mins it's a nice test but not that important to have I guess

2023-02-10 10:27 UTC, strickvl commented
@AlexejPenner @schustmi added a test. Not sure if it'll work, but let's see.

2023-02-14 09:58 UTC, stefannica requested changes

2023-02-14 09:58 UTC, stefannica commented on src/zenml/cli/server.py
> +        )
```suggestion
    except IllegalOperationError as e:
        cli_utils.warning(
            f"User '{username}' does not have sufficient permissions to "
            f"to access the server at '{url}'. Please ask the server "
            f"administrator to assign a role with permissions to your "
            f"username: {str(e)}"
        )
```

Or something similar. The reason being that the IllegalOperationError can be thrown in cases where the user only has read permissions or doesn't have permissions to modify the current project, or other situations such as these, so the message should be more generic and also include the original error.

2023-02-15 08:19 UTC, stefannica commented on tests/integration/functional/cli/test_server.py
> +        assert result.exit_code == 0
Forgot to mention this the last time, but could you please delete the user at the end of the test, to not clutter the external servers with left-over users ?

2023-02-15 08:19 UTC, stefannica approved these changes

2023-02-20 14:20 UTC, merged