Update huggingface token classification example
zenml-io/zenml pull request #1369
Opened 2023-03-01 13:24 UTC by strickvl

Updated the example to use some default values. (The example wasn't actually broken if you use the command listed in the `README.md`, but it fails when you try running the pipeline without specifying all the default values.) It now includes some core defaults (as per the documented suggestions) so it should run without errors for anyone not referring to the documentation.

Uncommenting the integration test will have to wait until other changes are made elsewhere.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-03-01 13:45 UTC, schustmi requested changes
All of my comments relate to the same issue: These values already get default values by the click options defined on the function. Maybe some of those (especially the ones which need to be different for token vs sequence classification, e.g. `dataset_name`) should not have a default value and then set the correct default dynamically?

2023-03-01 13:45 UTC, schustmi commented on examples/huggingface/run.py
> +            dataset_name=kwargs.get("dataset_name") or "conll2003",
I just checked the code and all of these already contain defaults from the click option? Wouldn't this `or` never be called?

Same for text_column and label_column

2023-03-01 13:45 UTC, schustmi commented on examples/huggingface/run.py
> +            epochs=epochs or 1,
`epochs` is an int and will therefore never be optional, the `or` won't be called (unless someone passes 0 but that's just a user error that should crash IMO)

2023-03-01 13:45 UTC, schustmi commented on examples/huggingface/run.py
> +            batch_size=batch_size or 16,
Same as epochs I think

2023-03-01 13:45 UTC, schustmi commented on examples/huggingface/run.py
> +            pretrained_model=pretrained_model or "distilbert-base-uncased",
Similar to the others, this already has a default value.

2023-03-02 10:06 UTC, safoinme approved these changes

2023-03-02 12:47 UTC, strickvl commented on examples/huggingface/run.py
> +    dataset_name: str,
Yep you're right.

2023-03-03 11:00 UTC, schustmi approved these changes

2023-03-03 11:00 UTC, merged