Changed to debug log
zenml-io/zenml pull request #1406
Opened 2023-03-13 09:31 UTC by htahir1

## Describe changes
I wanted to clean up log output

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-03-13 09:32 UTC, schustmi reviewed
I don't like this change tbh, we should reduce the amount but this is something security relevant which users should not do

2023-03-13 09:36 UTC, htahir1 commented
@schustmi I understand but this should only be given once and it shouldnt be in the constructor.. Otherwise its spammy as hell. I think we can raise it when people are registering a component

2023-03-13 09:39 UTC, schustmi commented
Registering seems like a good compromise to me!

2023-03-13 12:51 UTC, schustmi commented
Maybe we can add a parameter like `warn_about_plain_text_secrets` to `StackComponentConfig.__init__` which defaults to `False`, and then in `Client.create_stack_component(...)` we explicitly set it to `True`? This would only show the warning when registering a component, but the warning will not be shown in the dashboard (which should probably handle it differently anyway, e.g. using a dynamic warning message or automatically creating a secret)

2023-03-14 10:26 UTC, schustmi requested changes

2023-03-14 10:26 UTC, schustmi commented on src/zenml/config/secret_reference_mixin.py
> +                    logger.debug(
```suggestion
                    logger.warning(
```

2023-03-14 16:18 UTC, schustmi approved these changes

2023-03-14 19:30 UTC, merged