Add image builders to Examples
zenml-io/zenml pull request #1434
Opened 2023-03-22 12:23 UTC by safoinme

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-03-22 12:27 UTC, strickvl requested changes

2023-03-22 12:27 UTC, strickvl commented on examples/kubeflow_pipelines_orchestration/README.md
> +* An ***Image Builder** component that is responsible for building docker images
```suggestion
* An ***Image Builder** component that is responsible for building Docker images
```

2023-03-22 12:27 UTC, strickvl commented on examples/kubernetes_orchestration/README.md
> +`docker` image builder.
```suggestion
`local` image builder.
```

2023-03-22 12:27 UTC, strickvl commented on examples/spark_distributed_programming/README.md
> +We also need to register a **image builder** which will be used to build the
```suggestion
We also need to register an **image builder** which will be used to build the
```

2023-03-22 12:27 UTC, strickvl commented on examples/step_operator_remote_training/README.md
> +* An **Image Builder** which will be used to build the docker image that will
```suggestion
* An **Image Builder** which will be used to build the Docker image that will
```

2023-03-22 12:27 UTC, strickvl commented on examples/tekton_pipelines_orchestration/README.md
> +* An **Image Builder** that builds docker images for your pipeline steps.
```suggestion
* An **Image Builder** that builds Docker images for your pipeline steps.
```

2023-03-23 08:30 UTC, strickvl approved these changes
Looking good now. I guess we need to eventually do this to all projects, zenbytes, blog, and within the docs as well?

2023-03-23 08:52 UTC, safoinme commented
Yes i should apply same changes to other repos

2023-03-23 08:52 UTC, merged