recursive deletion added on stack
zenml-io/zenml pull request #1437
Opened 2023-03-24 07:24 UTC by KenmogneThimotee

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [* ] I have read the **CONTRIBUTING.md** document.
- [* ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [* ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [* ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-03-27 14:18 UTC, schustmi commented
Hey @KenmogneThimotee, thanks for the PR! The implementation looks good to me, however I would ask you to move the logic regarding the stack component deletion into the `Client.delete_stack(...)` method instead.

Some explanation on why: The CLI is only one of the ways to interact with ZenML, and some people prefer to instead use our `Client` class directly in code. For that reason we try to implement logic such as recursive deletion etc. in the client methods instead.

2023-03-27 14:26 UTC, KenmogneThimotee commented
ok, I will do that. Thanks.

2023-03-28 09:29 UTC, KenmogneThimotee commented
Do I need to keep the cli code because it informs the user of what is going to happen when it chooses to delete the stack recursively ?

2023-03-28 10:24 UTC, schustmi commented
Yes, I'd suggest keeping the confirmation code for the recursive delete inside the CLI, and if the user confirmed call `Client().delete_stack(..., recursive=True)` which handles the actual recursive deletion.

2023-03-29 09:02 UTC, schustmi requested changes

2023-03-30 02:03 UTC, KenmogneThimotee commented on src/zenml/client.py
> +            for stack_component in stack_components.items():
it makes more sense.

2023-03-30 02:05 UTC, KenmogneThimotee commented on src/zenml/client.py
> +            stack_components_not_free_for_deletion = []
The second array is not necessary but the first yes because I need to keep all the components that can be removed

2023-03-30 11:02 UTC, KenmogneThimotee reviewed
I added all review

2023-03-30 11:32 UTC, htahir1 requested changes
Minor nits from my side. Otherwise LGTM!

2023-03-30 11:32 UTC, htahir1 commented on src/zenml/client.py
> +
```suggestion
```

2023-03-30 11:36 UTC, schustmi requested changes

2023-03-30 11:36 UTC, schustmi commented on src/zenml/client.py
> +                logger.info(
I think this log is already happening in `self.delete_stack_component(...)` right? If that's the case, I would remove it here.

2023-03-31 12:47 UTC, schustmi commented
Awesome, thank you very much for the contribution!

2023-03-31 12:47 UTC, merged