feat: Set cloud function service account to the one defined in Vertex…
zenml-io/zenml pull request #1519
Opened 2023-05-05 16:20 UTC by francoisserra

… Orchestrator config

## Describe changes
When scheduling a pipeline on a stack that use the VertexAI Orchestrator, the ZenML framework creates a _cloud-scheduler_ and a _cloud-function_. The latter runs with the default project compute service account (`{project_number}-compute@developer.gserviceaccount.com`), as stated by the [GCP Cloud Function API doc](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v2#serviceconfig).
However running a GCP Cloud Function with the default compute service account is considered as a bad practice (at least in my company) since it has much more IAM permissions than it should have (see the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)

**This PR makes the created cloud function running with the same service account as the one set up in the `workload_service_account`** field of the [VertexOrchestratorConfig](https://apidocs.zenml.io/0.38.0/integration_code_docs/integrations-gcp/#zenml.integrations.gcp.flavors.vertex_orchestrator_flavor.VertexOrchestratorConfig)

Please note that will require the `workload_service_account` to have the right to impersonate to itself (i.e. have `roles/iam.serviceAccountUser` and `roles/iam.serviceAccountTokenCreator` on itself)

**However** if the community consider that I should create a dedicated config field in the [VertexOrchestratorConfig](https://apidocs.zenml.io/0.38.0/integration_code_docs/integrations-gcp/#zenml.integrations.gcp.flavors.vertex_orchestrator_flavor.VertexOrchestratorConfig) object, I can easily update my PR to achieve that.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-05-06 06:30 UTC, htahir1 commented
@francoisserra Thank you for the PR! I think a seperate service account might make sense to give more flexibility here (we can call it the `cloud_function_service_account`. That way the function service account can have the minimum possible permissions

2023-05-08 08:57 UTC, htahir1 commented
@francoisserra Just a small FYI, the latest release is aimed at tomorrow so if you'd like to do it before then I can try to get this in. If not then we can hold on until 0.40.0!

2023-05-08 09:06 UTC, fa9r requested changes
Great PR but I'd suggest making the change optional so we preserve backwards compatibility.

I.e., I'd suggest we:
- keep the current default behavior of using the default compute service account
- introduce a new config or setting `function_service_account` that one can set to have the cloud function assume another service account (such as the workload service account) instead.

2023-05-08 09:06 UTC, fa9r commented on src/zenml/integrations/gcp/google_cloud_function.py
> +                ),
```suggestion
                ) if function_service_account_email else None,
```

2023-05-08 09:06 UTC, fa9r commented on src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
> +            function_service_account_email=self.config.workload_service_account,
For this to work, we would accordingly need to add `function_service_account` as a field of `zenml.integrations.gcp.flavors.vertex_orchestrator_flavor.VertexOrchestratorConfig`

2023-05-08 09:42 UTC, francoisserra commented on src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
> +            function_service_account_email=self.config.workload_service_account,
Ok, fixed by 023cbc21109553d770f46bc507ff5c11e954556b

2023-05-08 09:42 UTC, francoisserra commented on src/zenml/integrations/gcp/google_cloud_function.py
> +                ),
see 023cbc21109553d770f46bc507ff5c11e954556b

2023-05-08 09:45 UTC, francoisserra commented
@fa9r @htahir1, I committed the requested changes.
Please let me know if it is OK, and if doing it in a hurry is a matter, I can wait for the 0.40.0.

2023-05-08 16:40 UTC, fa9r approved these changes
Looks good to me 👍

2023-05-08 17:03 UTC, htahir1 approved these changes
LGTM 🚀  Thanks for the contribution, ill merge now!

2023-05-08 17:03 UTC, merged