Airflow orchestrator improvements
zenml-io/zenml pull request #153
Opened 2021-11-02 16:24 UTC by schustmi

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
- Airflow orchestrator doesn't start by itself now but requires a CLI call (same for shutting down)
- Added ability to monitor an orchestrator via the CLI

2021-11-02 16:38 UTC, schustmi commented
This PR does not update the docs with the new Airflow Orchestrator workflow (yet). I will add it here or in a separate PR once we think the usage is how we want it to be.

2021-11-04 10:08 UTC, htahir1 requested changes
Great job!

2021-11-04 10:08 UTC, htahir1 commented on src/zenml/orchestrators/airflow/airflow_orchestrator.py
> +            shutil.copy2(dag_filepath, dags_directory)
Maybe use `path_utils`?

2021-11-04 10:08 UTC, htahir1 commented on src/zenml/orchestrators/airflow/airflow_orchestrator.py
> +            daemon.stop_daemon(self.pid_file, kill_children=True)
Best line of code ever written.

2021-11-04 10:08 UTC, htahir1 commented on src/zenml/utils/daemon.py
> +
Please make a note that it doesnt work on Windows

2021-11-04 10:54 UTC, schustmi commented on src/zenml/cli/config.py
> +def _get_orchestrator(
Actually I remember why I put it here (both service and stack already have a way to get the active orchestrator or by key): The reason was that I wanted do declare something on the CLI if we fallback to the active orchestrator, so it shouldn't be part of the other classes I think. I'd argue in this case it should probably stay in the cli orchestrator file, wdyt?

2021-11-04 15:22 UTC, merged