Adjust Seldon Steps and Examples to New Pipeline Interface
zenml-io/zenml pull request #1560
Opened 2023-05-24 13:25 UTC by fa9r

## Describe changes
I adjusted the Seldon integration steps and corresponding examples to the new pipeline/step syntax.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-06-13 07:33 UTC, schustmi requested changes

2023-06-13 07:33 UTC, schustmi commented on examples/seldon_deployment/steps/common/prediction_service_loader.py
> +class SeldonDeploymentLoaderStepParameters(BaseParameters):
I guess this can be deleted?

2023-06-16 11:22 UTC, schustmi approved these changes

2023-06-16 13:55 UTC, safoinme approved these changes

2023-06-16 14:45 UTC, merged