Implement Azure service connector
zenml-io/zenml pull request #1589
Opened 2023-06-02 20:27 UTC by stefannica

## Describe changes
Implement the Azure service connector.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-06-04 08:33 UTC, AlexejPenner approved these changes
Looks pretty good to me, that 1700 line file took some time to get through. Not sure I understood every smallest aspect of it so might make sense to also get a review from someone who reviewd the original connectors PR

2023-06-05 08:59 UTC, fa9r reviewed
Overall this looks good to me, However, similar to @AlexejPenner, I found it quite hard to review this in detail without having reviewed the original connectors PR, so I would suggest waiting for a review from @schustmi (in addition to docs and tests) before merging this. 

High-level I was wondering why Azure/AWS/GCP all require k8s as a dependency now. In a sense this is not ideal since I would now need to install k8s even if I just want to use, e.g., the GCP artifact store. Do you think it might make sense to decouple the connectors from the existing integrations for that reason? Or perhaps to move the GCP/Azure artifact store implementations to separate integrations similar to how we have `aws` and `s3`?

Also, I think long texts like the `description` of your new models would be much easier to consume, review, and maintain if they lived in the docs. Thus, I'd propose to turn them into docs and to replace them with short one-line descriptions that include links to the relevant pages instead.

2023-06-05 08:59 UTC, fa9r commented on src/zenml/integrations/kubernetes/service_connectors/kubernetes_service_connector.py
> +                k8s_conf.cert_file = temp_path
I see this logic duplicated several times below, should we move this to a separate util function perhaps? TBH I also don't fully understand what it does so having this in one place with corresponding docstrings would be helpful as well.

2023-06-05 08:59 UTC, fa9r commented on src/zenml/integrations/azure/service_connectors/azure_service_connector.py
> +permissions of the managed identity may need to be adjusted to allows listing
```suggestion
permissions of the managed identity may need to be adjusted to allow listing
```

2023-06-05 08:59 UTC, fa9r commented on src/zenml/integrations/azure/service_connectors/azure_service_connector.py
> +are not represented by other, more specific resource type, like Azure blob
```suggestion
are not represented by other, more specific resource types, like Azure blob
```

2023-06-05 08:59 UTC, fa9r commented on src/zenml/integrations/azure/service_connectors/azure_service_connector.py
> +        # We need to extract the container name from the provided resource ID
include in docstrings above?

2023-06-05 18:45 UTC, stefannica commented
> High-level I was wondering why Azure/AWS/GCP all require k8s as a dependency now. In a sense this is not ideal since I would now need to install k8s even if I just want to use, e.g., the GCP artifact store. Do you think it might make sense to decouple the connectors from the existing integrations for that reason? Or perhaps to move the GCP/Azure artifact store implementations to separate integrations similar to how we have `aws` and `s3`?

@fa9r  The kubernetes library is used in so many of our stack components that it's almost as fundamental to ZenML as the docker library. But more to the point, all these integrations are cloud provider integrations that include some form of managed Kubernetes and the connectors rely on the k8s library to generate kubernetes specific API credentials.

Decoupling connectors from integrations make it even more complicated to deal with dependencies, because the pipeline code now also needs to be aware of which connectors are linked to which components in order to track and install the necessary packages (just like we do with stack components and integrations). The compromise of including kubernetes as a dependency for all integrations that deal with cloud providers is the simplest way out of a situation that only exacerbates the dependency hell.

> 
> Also, I think long texts like the `description` of your new models would be much easier to consume, review, and maintain if they lived in the docs. Thus, I'd propose to turn them into docs and to replace them with short one-line descriptions that include links to the relevant pages instead.

I disagree. In fact, I think in a future where connectors and integrations exist separately from the ZenML core repository (i.e. Hub plugins), some form of documentation needs to live closer to the descriptors that encode what each plugin contains and how to use it. But more specifically for service connectors, the documentation embedded in the code is extensively used to provide a more interactive CLI experience and soon in more interactive dashboard experience as well.

You do have a point however that we do need to cover these service connectors in the ZenML docs and right now the real problem is that these same docs are duplicated there as well. A situation for which I don't have a solution at the moment, but maybe we can think of one as part of the future "zenml integrations as Hub plugins" movement.

2023-06-06 06:43 UTC, fa9r approved these changes
Looks good to me, I also don't have strong opinions about the general suggestions above, so happy to keep those as they are if you prefer that. 

Duplication between docs and src is a general problem we have so I don't expect that to be solved as part of this PR. Ideally, we should find a way to "import" text/code in our docs from other places but I think gitbook doesn't allow that, so nothing we can do about it right now I would say.

Thus, happy to approve, but, as I mentioned above, please wait for @schustmi's review before merging :)

2023-06-06 14:55 UTC, schustmi requested changes
Love it, had a quite detailed look but only have some minor comments! 🎉

(Apart from unit tests, but I completely understand that mocking the entire Azure framework would be a huge effort)

2023-06-06 14:55 UTC, schustmi commented on src/zenml/integrations/azure/service_connectors/azure_service_connector.py
> +                    if account.id.split("/")[4] == self.config.resource_group
I've seen this `split("/")[4]` in a few places now, should we extract it in some function in case it needs to be updated in the future?

2023-06-06 16:57 UTC, stefannica commented on src/zenml/container_registries/azure_container_registry.py
> +            connector_type="azure",
I did it for the `docker-registry` part, but I can't import here constants from the Azure integration. Not sure how to solve this without polluting the global constants namespace with integration specific constants, which I'd rather not do.

2023-06-06 17:11 UTC, stefannica commented on src/zenml/integrations/azure/service_connectors/azure_service_connector.py
> +            assert expires_at is not None
Yes, there are provisions in the ServiceConnector base class that validate the configuration before this function is even called: https://github.com/zenml-io/zenml/blob/main/src/zenml/models/service_connector_models.py#L193

2023-06-07 07:25 UTC, schustmi commented on src/zenml/container_registries/azure_container_registry.py
> +            connector_type="azure",
Ah I see, because this file is still in core ZenML, makes sense

2023-06-07 07:27 UTC, schustmi approved these changes

2023-06-07 19:18 UTC, merged