Fix for bentoml integration/example
zenml-io/zenml pull request #1604
Opened 2023-06-08 13:46 UTC by strickvl

Fixes for bentoml example. Requires:

- some daemon checks to be commented out from `local_service.py` 
- as well as pinning BentoML to 1.0.10 (whereas the current version is 1.0.21).

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-06-09 07:11 UTC, stefannica requested changes

2023-06-09 07:11 UTC, stefannica commented on examples/bentoml_deployment/steps/bento_builder.py
> +            "zenml_version": "0.40.1",
```suggestion
            "zenml_version": __version__,
```

2023-06-09 07:11 UTC, stefannica commented on src/zenml/services/local/local_service.py
> +                #     return None
Could you keep this code but make it a warning ?

2023-06-12 15:14 UTC, fa9r commented
Closing in favor of #1604

2023-06-12 15:14 UTC, closed without merging