Added some error handling in gcp cloud function scheduling
zenml-io/zenml pull request #1634
Opened 2023-06-19 15:08 UTC by htahir1

## Describe changes
To be tested, but added the basic code for now

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-06-19 15:11 UTC, htahir1 commented on src/zenml/integrations/gcp/google_cloud_function.py
> +            error_messages = ', '.join([msg.text for msg in response.state_messages])
```suggestion
            error_messages = ', '.join([msg.message for msg in response.state_messages])
```

2023-06-22 07:10 UTC, htahir1 commented on src/zenml/integrations/gcp/google_cloud_function.py
> +            error_messages = ', '.join([msg.message for msg in response.state_messages])
```suggestion
            error_messages = ", ".join([msg.message for msg in response.state_messages])
```

2023-06-23 08:42 UTC, bcdurak requested changes
I made a suggestion by adding a small adjustment to the if condition.

2023-06-23 08:47 UTC, bcdurak approved these changes

2023-06-26 08:28 UTC, stefannica approved these changes

2023-06-26 10:18 UTC, htahir1 commented
@bcdurak Could you kindly test this locally and merge if it works out as we expect?

2023-06-26 12:03 UTC, bcdurak commented
@htahir1 on it!

2023-06-27 08:46 UTC, merged