Removal/FRW-2162 deprecate examples cli
zenml-io/zenml pull request #1693
Opened 2023-07-17 10:32 UTC by avishniakov

## Describe changes
I added deprecation note for `example` CLI to warn users about upcoming changes. Details on new mechanism will follow later, for now it is just an announcement.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

2023-07-17 10:47 UTC, avishniakov commented
> @avishniakov could you add it [to the deprecations internal docs](https://www.notion.so/zenml/Deprecations-903bcaacb5c04954b9f6133b3340a312) as well? We try to keep track of what we're deprecating / how long things have been in that state etc.

Thanks for pointing, added 👍🏼

2023-07-17 13:05 UTC, strickvl requested changes
I think we'll also need to have these messages on all the other `zenml example...` CLI commands as well.

2023-07-17 13:05 UTC, strickvl commented on src/zenml/cli/example.py
> +        "and will be no longer maintained by the ZenML core team after that."
Sorry for the formatting (doing it in web UI) but the text suits better I think.

2023-07-17 13:28 UTC, avishniakov commented on src/zenml/cli/example.py
> +        "and will be no longer maintained by the ZenML core team after that."
Thanks, sounds better - added in [f36d475](https://github.com/zenml-io/zenml/pull/1693/commits/f36d475d77c25eb024be6eec08c46052975f48df)

2023-07-17 13:39 UTC, strickvl requested changes
Can you add the message to the other CLI commands as well?

2023-07-17 15:54 UTC, strickvl approved these changes
🙌

2023-07-17 15:56 UTC, strickvl approved these changes
Approved, but @htahir1 do you think we also should remove the instructions to use the examples CLI command from all the `examples` READMEs? Or leave it since they're being removed anyway soon?

2023-07-18 06:50 UTC, htahir1 approved these changes
LGTM. If I was to nitpick I would indicate in the message to the user that they should manually clone the examples and follow the instructions in the example README but not neccessary

@strickvl  As they are being removed, i wouldnt really do the effort right now (as these are deprecations anyway, not removals)

2023-07-18 07:12 UTC, merged