Feature/configurable service account for seldon predictor service
zenml-io/zenml pull request #1725
Opened 2023-07-31 15:25 UTC by Johnyz21

## Describe changes
I've added the ability to deploy Seldon Core V1 Models with a custom service account

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/component-gallery/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-08-07 07:43 UTC, safoinme requested changes
Can you please add the `serviceAccountName` to the docs section where `SeldonDeploymentConfig` is mentioned, you can find it [here](https://github.com/zenml-io/zenml/blob/77b399754e6069afc2ec9a0de9d608d4211eca8c/docs/book/user-guide/component-guide/model-deployers/seldon.md#how-do-you-use-it)!
Otherwise looks good

2023-10-23 11:04 UTC, stefannica approved these changes

2023-11-02 11:28 UTC, Johnyz21 commented
> Can you please add the `serviceAccountName` to the docs section where `SeldonDeploymentConfig` is mentioned, you can find it [here](https://github.com/zenml-io/zenml/blob/77b399754e6069afc2ec9a0de9d608d4211eca8c/docs/book/user-guide/component-guide/model-deployers/seldon.md#how-do-you-use-it)! Otherwise looks good

Updated the docs 🙌

2023-11-14 14:46 UTC, safoinme approved these changes

2023-11-18 15:34 UTC, merged