WIP: Reduce CI runner count
zenml-io/zenml pull request #1777
Opened 2023-09-01 14:50 UTC by strickvl

Implementing a refactoring of our runner matrix to reduce total numbers of runners needed for our CI tests.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-09-02 10:39 UTC, fa9r approved these changes
LGTM!

2023-09-04 05:38 UTC, AlexejPenner approved these changes
:seal:

2023-09-04 06:57 UTC, avishniakov requested changes
Hey, nice step forward! Left a few comment and we need to find out why CI failed (looks like there are unseen errors with setup happening)

2023-09-04 06:57 UTC, avishniakov commented on .github/workflows/integration-test.yml
> +        uses: jenseng/dynamic-uses@v1
We don't need dynamic uses here anymore - uses are nor longer dynamic.

2023-09-04 06:57 UTC, avishniakov commented on .github/workflows/integration-test.yml
> +        uses: jenseng/dynamic-uses@v1
same

2023-09-04 06:57 UTC, avishniakov commented on .github/workflows/setup-python-environment.yml
> +name: Setup Python Environment, Lint and Unit Test
I would not touch this, cause it is used elsewhere (like inside Integration tests), so I'd better repoint CI jobs to `lint-unit-test.yaml` for now and keep this untouched (or, better, revisit how it is used and adjust).
I'm pretty sure that with this setup Integration tests are also running a full set of units (see step `Setup environment` there)

2023-09-04 09:29 UTC, avishniakov commented on .github/workflows/setup-python-environment.yml
> +name: Setup Python Environment, Lint and Unit Test
My bad: misread the structure of actions/scripts. All good here

2023-09-04 13:50 UTC, avishniakov approved these changes
Good to merge 👍🏼

2023-09-04 13:54 UTC, avishniakov commented
@strickvl let's merge it before https://github.com/zenml-io/zenml/pull/1766 - this one is more critical and I'll resolve conflicts there.

2023-09-04 14:11 UTC, strickvl commented
@avishniakov agreed. the failing test is lightgbm integration test, but I ran it locally and works fine. WDYT? the failure message doesn't really help debug what's up there. And the test works everywhere else.

2023-09-04 14:12 UTC, avishniakov commented
> @avishniakov agreed. the failing test is lightgbm integration test, but I ran it locally and works fine. WDYT? the failure message doesn't really help debug what's up there. And the test works everywhere else.

I would merge it - don't see this failure anyhow related to your work in this PR.

2023-09-04 14:13 UTC, merged