Fix MLflow registry methods with empty metadata
zenml-io/zenml pull request #1843
Opened 2023-09-27 09:50 UTC by fa9r

## Describe changes
The following model registry methods were all broken if no metadata was provided:
- register_model_version
- update_model_version
- list_model_versions

Problem: the function declarations specified `pydantic.Field` as default value which is only viable for Pydantic models and not for regular Python functions.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-09-27 09:53 UTC, avishniakov requested changes
The template needs a fix in another place, rest is good to go.

2023-09-27 09:53 UTC, avishniakov commented on examples/e2e/steps/inference/inference_get_current_version.py
> -        metadata={},
This should be fixed on template side - there is a CI auto-refreshing it.

2023-09-27 09:53 UTC, avishniakov commented on examples/e2e/steps/promotion/promote_get_versions.py
> -        metadata={},
This should be fixed on template side - there is a CI auto-refreshing it.

2023-09-27 09:53 UTC, avishniakov commented on examples/e2e/steps/promotion/promote_get_versions.py
> -        metadata={},
This should be fixed on template side - there is a CI auto-refreshing it.

2023-09-27 09:53 UTC, avishniakov commented on examples/e2e/steps/promotion/promote_metric_compare_promoter.py
> -                metadata={},
This should be fixed on template side - there is a CI auto-refreshing it.

2023-09-27 09:53 UTC, avishniakov commented on examples/e2e/steps/promotion/promote_metric_compare_promoter.py
> -            metadata={},
This should be fixed on template side - there is a CI auto-refreshing it.

2023-09-27 13:06 UTC, avishniakov commented on examples/e2e/steps/inference/inference_get_current_version.py
> -        metadata={},
https://github.com/zenml-io/template-e2e-batch/pull/10

2023-09-28 06:34 UTC, avishniakov approved these changes
After CI completes and brings template updates here - good to go 👍🏼

2023-09-28 07:12 UTC, strickvl approved these changes

2023-10-02 11:03 UTC, merged