Connect to Service-connector at component registration
zenml-io/zenml pull request #1858
Opened 2023-10-04 18:32 UTC by safoinme

## Describe changes
Adding the ability to set a service connector to connect to when registering the component for the first time to avoid running 2 commands. The implementation uses the function used to connect and calls it after the component is registered to ensure all validation we have in the connect command is called without actually re-writing it.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] I have updated the documentation if my change requires a change to docs.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR targets `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-10-05 08:25 UTC, stefannica requested changes

2023-10-05 08:25 UTC, stefannica commented on src/zenml/cli/stack_components.py
> +
You also need a resource ID argument for some resource types, such as cloud Kubernetes clusters. You're also missing out on the best part of linking a component to a connector: the interactive mode.

2023-10-05 08:25 UTC, stefannica commented on src/zenml/cli/stack_components.py
> +        connect_stack_component_with_service_connector(
you probably need to run this only `if connector`

2023-10-06 08:25 UTC, fa9r approved these changes
`connect_stack_component_with_service_connector` needs to be in the `if` condition, otherwise LGTM 👍

2023-10-10 14:16 UTC, merged