Fixing the migration issues
zenml-io/zenml pull request #1945
Opened 2023-10-13 13:09 UTC by bcdurak

## Describe changes
I fixed the problems caused by the alembic migration.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [X] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [X] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-10-13 15:24 UTC, fa9r requested changes
Changes look good to me, however before we merge I'd suggest we:
- combine the two new migrations into one
- either implement the downgrade correctly or just raise a `NotImplementedError`

2023-10-13 15:24 UTC, fa9r commented on src/zenml/zen_stores/migrations/versions/37835ce041d2_optimizing_database.py
> -        batch_op.add_column(
downgrade is not fully reflective of the upgrade changes

2023-10-14 14:17 UTC, bcdurak commented
@fa9r I implemented the suggested changes, merged two scripts into one, and put a `NonImplementedError` for the downgrade.

2023-10-14 15:07 UTC, fa9r reviewed
죽을래?

2023-10-14 15:08 UTC, fa9r approved these changes

2023-10-15 12:34 UTC, merged

2023-10-16 06:38 UTC, AlexejPenner commented on src/zenml/zen_stores/migrations/versions/6f707b385dc1_fix_model_artifacts.py
>  branch_labels = None
@bcdurak changing this in the upgrade tree seems very wrong to me, I think this is rewriting history in a way that might break things for people who are running on 0.45.0 now. Is this file somethign that was merged into develop after the 0.45.0 release?

2023-10-16 06:42 UTC, AlexejPenner commented on src/zenml/zen_stores/migrations/versions/6f707b385dc1_fix_model_artifacts.py
>  branch_labels = None
ah went to investigate, all good with this.