Updating README.md
zenml-io/zenml pull request #1986
Opened 2023-10-24 15:38 UTC by znegrin

## Describe changes
I updated the README.md file, adding new images and removing the outdated ones.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-10-24 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zenml-io/zenml?pullRequest=1986) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zenml-io/zenml?pullRequest=1986) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zenml-io/zenml?pullRequest=1986) it.</sub>

2023-10-24 15:42 UTC, strickvl requested changes

2023-10-24 15:42 UTC, strickvl commented on README.md
> +    <img alt="ZenML Logo" src="docs/book/.gitbook/assets/header.png" alt="ZenML">
```suggestion
    <img alt="ZenML Logo" src="docs/book/.gitbook/assets/header.png" alt="ZenML logo">
```

2023-10-25 08:45 UTC, htahir1 requested changes
nice! I have a few comments.

First, the banner headline is a bit  outdated. It should be something like "ZenML abstracts the infrastructure complexity for ML Engineers without locking you into any vendor" 

Second, this part of the README also needs an update.. it feels like its overloaded with information... maybe removing some things or restructuring might help?

![image](https://github.com/zenml-io/zenml/assets/4792082/5f4edbf8-2b12-4ad4-9dde-d2ee0bebb7bd)

2023-10-25 09:33 UTC, znegrin commented
@htahir1 I just pushed some changes to the header:
- Replaced the image with the new text.
- Moved the header image to the top.
- Changed the badges to make them more compact and changed the colors to our primary palette.
- Removed some of the contents as requested.

2023-10-25 10:33 UTC, merged