move db init container to seperated job annotated with helm annotations
zenml-io/zenml pull request #2021
Opened 2023-11-03 14:13 UTC by safoinme

## Describe changes
This PR implements a pivotal change in our Helm chart deployment process by replacing the existing init container for database migration with a dedicated Helm Job. To ensure timely execution of database migration, Helm hooks with `pre-install` and `pre-upgrade` annotations are applied. This enhancement resolves migration issues arising when multiple replicas are deployed, guaranteeing database consistency and aligning the migration Job's execution precisely before the deployment. Extensive testing confirms the smooth operation of this new approach, both with single and multiple replicas in a Kubernetes cluster. The PR also adheres to Helm best practices by setting `helm.sh/hook-delete-policy` to `hook-succeeded`. Reviewers, please verify the code changes and execution order during the Helm installation and upgrade.

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-11-06 08:26 UTC, stefannica requested changes
This is an amazing solution ! So good, in fact, that I think we might even be able to use something similar to implement automated DB downgrades (e.g. for rollbacks or even zenml server downgrades), which is something that would not have been previously possible with the init container.

2023-11-06 08:26 UTC, stefannica commented on src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
> +{{- if .Values.zenml.database.url }}
I think this condition should guard the entire job definition instead of just its `spec`.

2023-11-06 08:45 UTC, stefannica commented on src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
> +    "helm.sh/hook-delete-policy": hook-succeeded
```suggestion
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
```
This way, previous invocations of jobs that have failed are also cleaned up when the helm chart is re-applied.

2023-11-06 08:57 UTC, stefannica commented
> This is an amazing solution ! So good, in fact, that I think we might even be able to use something similar to implement automated DB downgrades (e.g. for rollbacks or even zenml server downgrades), which is something that would not have been previously possible with the init container.

I went a bit overboard here and forgot the real reason why we can't implement DB downgrades is that we need the new version image during rollback, which isn't possible ATM.

2023-11-06 10:15 UTC, stefannica commented
> > This is an amazing solution ! So good, in fact, that I think we might even be able to use something similar to implement automated DB downgrades (e.g. for rollbacks or even zenml server downgrades), which is something that would not have been previously possible with the init container.
> 
> I went a bit overboard here and forgot the real reason why we can't implement DB downgrades is that we need the new version image during rollback, which isn't possible ATM.

I just got an idea of how we might be able to implement this after all:

* always use `latest` as the container image used for the DB migration job
* pass the target zenml version as a parameter (command line argument) to the job
* the job figures out what the current DB version is, compares it to the one received as a parameter and performs an upgrade/downgrade as the case may be

2023-11-07 09:29 UTC, stefannica approved these changes

2023-11-07 10:46 UTC, strickvl approved these changes

2023-11-07 18:01 UTC, merged