Feature/revamp model endpoints
zenml-io/zenml pull request #2035
Opened 2023-11-09 14:24 UTC by AlexejPenner

## Describe changes
I made model_versions their own root route - for the purpose of preserving some of the implicit functionality of model versions I left two endpoints on the /models route to allow users to fetch model versions based on latest, stage or name

![image](https://github.com/zenml-io/zenml/assets/38859294/f1688d2e-9c35-48e3-abf3-58ce180f7b50)

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-11-09 14:53 UTC, AlexejPenner commented
@avishniakov please let me know if I am missing anything obvious - I have opted to keep the behaviour for get and list methods consistent, but everything else now relies on the new more atomic interface

2023-11-09 15:41 UTC, avishniakov approved these changes
One slash missing, other than that - if tests pass, all good.

2023-11-09 15:41 UTC, avishniakov commented on src/zenml/zen_server/routers/model_versions_endpoints.py
> +    + "{model_version_artifact_link_name_or_id}",
```suggestion
    + "/{model_version_artifact_link_name_or_id}",
```

2023-11-09 15:41 UTC, avishniakov requested changes
Fix status, cause of slash :)

2023-11-13 13:32 UTC, AlexejPenner commented
@avishniakov do you have any manual testing flow that you used, that I can do to ensure no functionality is lost?

2023-11-13 13:45 UTC, avishniakov commented
> @avishniakov do you have any manual testing flow that you used, that I can do to ensure no functionality is lost?

I think, you can run the E2E template on a remote (docker) setup - should be good enough. Otherwise, it is pretty well covered with tests already.

2023-11-15 13:27 UTC, fa9r reviewed
A lot of the changes introduced here clash with #2044, please consolidate this first

2023-11-15 16:59 UTC, AlexejPenner commented on src/zenml/models/model_models.py
> +        return mv
@avishniakov I discovered this value was never set, i implemented a temporary fix but would leave it up to you to decide where to handle this

2023-11-16 10:17 UTC, merged