Fix tag resource id generator
zenml-io/zenml pull request #2056
Opened 2023-11-16 16:34 UTC by avishniakov

## Describe changes
I fixed tag<>resource ID generator to fix the issue of manipulating migrated tags properly. Before the change, it was not possible to detach migrated tags from the tagged entities.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/stacks-and-components/component-guide) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2023-11-16 17:38 UTC, avishniakov commented on src/zenml/zen_stores/migrations/versions/6119cd9b93c2_tags_table.py
> +                    f"('{uuid4().hex}', "
Updating old migration just to make sure users upgrading from the old versions will not experience issues here.

2023-11-17 10:36 UTC, stefannica requested changes

2023-11-17 10:36 UTC, stefannica commented on src/zenml/zen_stores/schemas/tag_schemas.py
> +            id=uuid4(),
```suggestion
```

You don't really need to generate a UUID here anymore, there's a default factory set in the base class.

2023-11-17 10:43 UTC, strickvl approved these changes
LGTM

2023-11-17 10:58 UTC, stefannica approved these changes

2023-11-20 07:57 UTC, merged