Reduce `ExternalArtifact` capabilities to value only
zenml-io/zenml pull request #2335
Opened 2024-01-22 11:56 UTC by avishniakov

## Describe changes
I reduced the function an `ExternalArtifact` can perform to only `value` inputs. Rest is covered by `Client()` or `Model` methods going forward.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-01-22 12:59 UTC, avishniakov commented
> Please make sure the docs are updated accordingly :-)

Yeah, sure, it is WIP still, as mentioned in the description. I will ensure all cases are working fine and clean-up the docs in parallel.

2024-01-23 13:40 UTC, strickvl requested changes

2024-01-23 13:40 UTC, strickvl commented on tests/integration/functional/steps/test_external_artifact.py
can we add a test for the failure scenario where we hit a RuntimeError when there's no value?

2024-01-23 16:26 UTC, avishniakov commented on docs/book/user-guide/starter-guide/manage-artifacts.md
> +    ArtifactConfig(name="my_model", is_model_artifact=True, tags=["SVC", "trained"]),
Just put the whole code into IDE and linted - this is the result. Code is the same.

2024-01-23 16:30 UTC, avishniakov commented on src/zenml/artifacts/external_artifact.py
> +            raise RuntimeError("Cannot upload an empty artifact.")
Yeah, both. It can only happen if someone heavily misused this class. But it doesn't do any harm and calms down mypy. I rephrased a bit for clarity.

2024-01-23 16:34 UTC, avishniakov commented on tests/integration/functional/steps/test_external_artifact.py
Added

2024-01-23 17:16 UTC, strickvl approved these changes

2024-01-24 08:05 UTC, avishniakov commented
/fulltest

2024-01-24 10:04 UTC, strickvl commented
/fulltest

2024-01-24 23:05 UTC, safoinme approved these changes

2024-01-24 23:05 UTC, safoinme commented on src/zenml/artifacts/external_artifact.py
> +            logger.info("Finished uploading external artifact %s.", self._id)
Can we standardize the use of f-Strings
```suggestion
            logger.info(f"Finished uploading external artifact {self._id}.")
```

2024-01-24 23:05 UTC, safoinme commented on src/zenml/artifacts/external_artifact.py
> +            logger.info("Uploading external artifact to '%s'.", uri)
```suggestion
            logger.info(f"Uploading external artifact to '{uri}'.")
```

2024-01-30 15:00 UTC, avishniakov commented
Closed in favor of https://github.com/zenml-io/zenml/pull/2375

2024-01-30 15:00 UTC, closed without merging