Some imp docs updates
zenml-io/zenml pull request #2463
Opened 2024-02-22 16:23 UTC by htahir1

## Describe changes
I fixed a few things and made zenml cloud more visible, as we offer a free account now.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [x] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-02-22 16:58 UTC, strickvl commented on README.md
> +ZenML is a cross between a classic pipeline tool like [Airflow](https://airflow.apache.org/) and a metadata tracking service like [MLflow](https://mlflow.org/).
interesting positioning!

2024-02-22 16:58 UTC, strickvl commented on README.md
> +- Let's you create simple, pythonic [ML pipelines that run locally](https://docs.zenml.io/user-guide/starter-guide/create-an-ml-pipeline) and can be easily be run on any [orchestration backend](https
```suggestion
- Lets you create simple, pythonic [ML pipelines that run locally](https://docs.zenml.io/user-guide/starter-guide/create-an-ml-pipeline) and can be easily be run on any [orchestration backend](https://docs.zenml.io/user-guide/production-guide/cloud-orchestration).
```

2024-02-22 16:58 UTC, strickvl commented on README.md
> +- Connecting your [secret store](https://docs.zenml.io/user-guide/advanced-guide/secret-management) to your ML workflows
```suggestion
- Connecting your [secret store](https://docs.zenml.io/user-guide/advanced-guide/secret-management) to your ML workflows.
```

2024-02-22 16:58 UTC, strickvl commented on README.md
> +- Automatically creating visualizations and tracking experiments: ZenML [integrates to experiment trackers](https://docs.zenml.io/stacks-and-components/component-guide/experiment-trackers) that are m
```suggestion
- Automatically creating visualizations and tracking experiments: ZenML [integrates with experiment trackers](https://docs.zenml.io/stacks-and-components/component-guide/experiment-trackers) that are much more specialized at doing this.
```

2024-02-22 16:58 UTC, strickvl commented on README.md
> +- Packaging and deploying models - ZenML tracks models and metadata, which you can then use to deploy the models more easily.. See the [ZenML model deployers](https://docs.zenml.io/stacks-and-compone
```suggestion
- Packaging and deploying models - ZenML tracks models and metadata, which you can then use to deploy the models more easily. See the [ZenML model deployers](https://docs.zenml.io/stacks-and-components/component-guide/model-deployers) integrations for more details.
```

2024-02-22 16:58 UTC, strickvl commented on README.md
> +You should ZenML if you resonate with one or more of the following problems:
```suggestion
You should ZenML if one or more of the following problems resonates with you:
```

2024-02-22 16:58 UTC, strickvl commented on README.md
> +- You are working with ML use-cases that require repeatability and reproducibility.
```suggestion
- You are working with ML use cases that require repeatability and reproducibility.
```

2024-02-23 09:02 UTC, strickvl approved these changes

2024-02-23 10:25 UTC, strickvl requested changes
Better now. just a few remaining nits / questions.

2024-02-23 10:25 UTC, strickvl commented on README.md
> +ZenML aims to optimize your entire machine learning lifecycle - you'll be 80% faster to production, generate 3x more models, and massively reduce your cloud spend.
maybe instead of "aims to", something more active? 

- ZenML optimizes your entire...
- ZenML is all about optimizing your...
- etc

2024-02-23 10:25 UTC, strickvl commented on README.md
> +ZenML aims to optimize your entire machine learning lifecycle - you'll be 80% faster to production, generate 3x more models, and massively reduce your cloud spend.
also feels like maybe these very precise numbers need links to user case studies etc. without links it feels a bit arbitrary? (Not sure how others would read it, though).

2024-02-23 10:25 UTC, strickvl commented on README.md
> +ZenML offers a systematic approach to structuring your machine learning codebase for a seamless transition to production. It's an ideal solution for teams grappling with establishing an internal stan
```suggestion
ZenML offers a systematic approach to structuring your machine learning codebase for a seamless transition to production. It's an ideal solution for teams grappling with establishing an internal standard for coordinating ML operations. ZenML provides not just a tool, but a workflow strategy that guides you in integrating all your tools and infrastructure effectively.
```

2024-02-23 10:56 UTC, strickvl approved these changes

2024-02-23 11:59 UTC, bcdurak requested changes

2024-02-23 11:59 UTC, bcdurak commented on docs/book/.gitbook/assets/zenml-why.png:Zone.Identifier
What is this file?

2024-02-23 11:59 UTC, bcdurak commented on docs/book/deploying-zenml/zenml-cloud/zenml-cloud.md
> +One of the most straightforward paths to start with a deployed ZenML server is to use  [ZenML Cloud](https://zenml.io/cloud). ZenML Cloud eliminates the need for you to dedicate time and resources to
```suggestion
One of the most straightforward paths to start with a deployed ZenML server is to use [ZenML Cloud](https://zenml.io/cloud). ZenML Cloud eliminates the need for you to dedicate time and resources to deploy and manage a ZenML server, allowing you to focus primarily on your MLOps workflows.
```

2024-02-23 11:59 UTC, bcdurak commented on docs/book/getting-started/installation.md
> +For deployment of ZenML, you have the option to either [self-host](../deploying-zenml/zenml-self-hosted/zenml-self-hosted.md) or register for a free account on [ZenML Cloud](https://cloud.zenml.io/?u
```suggestion
For the deployment of ZenML, you have the option to either [self-host](../deploying-zenml/zenml-self-hosted/zenml-self-hosted.md) it or register for a free account on [ZenML Cloud](https://cloud.zenml.io/?utm_source=docs&utm_medium=referral_link&utm_campaign=cloud_promotion&utm_content=signup_link).
```

2024-02-23 11:59 UTC, bcdurak commented on README.md
> +  <h3 align="center">Create a MLOps workflow for your entire team.</h3>
```suggestion
  <h3 align="center">Create an MLOps workflow for your entire team.</h3>
```

2024-02-23 11:59 UTC, bcdurak commented on README.md
> +ZenML optimizes your entire machine learning lifecycle - you'll be 80% faster to production, generate 3x more models, and massively reduce your cloud spend.
I think these numbers can be very situational and it feels a bit off displaying them without any resources to back it up.

2024-02-23 11:59 UTC, bcdurak commented on README.md
> +- Collaboration and hand-overs between multiple data scientists and ML engineers is difficult.
```suggestion
- Collaboration and hand-overs between multiple teams is difficult.
```

2024-02-23 11:59 UTC, bcdurak commented on README.md
> +- Automatically containerize and deploy your workflows to the cloud, connected to your [code repository](https://docs.zenml.io/user-guide/production-guide/connect-code-repository).
```suggestion
- Automatically containerizing and deploying your workflows to the cloud, connected to your [code repository](https://docs.zenml.io/user-guide/production-guide/connect-code-repository).
```

2024-02-23 12:13 UTC, merged

2024-02-23 12:15 UTC, htahir1 commented
@strickvl @bcdurak thanks for the reviews. i merged and backported