Interact with feature gate
zenml-io/zenml pull request #2492
Opened 2024-03-01 21:51 UTC by AlexejPenner

## Describe changes
Relates to https://github.com/zenml-io/zenml-cloud-api/pull/140 over on the cloud side

needs https://github.com/zenml-io/zenml/pull/2464 to go in first to geth the organization

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-03-07 15:18 UTC, safoinme submitted a review, later dismissed

2024-03-07 15:18 UTC, safoinme commented on src/zenml/zen_server/rbac/endpoint_utils.py
any specific reason why this file doesn't have copyright header

2024-03-07 15:18 UTC, safoinme commented on src/zenml/zen_server/utils.py
> +    return _feature_gate
```suggestion
    """Return the initialized Feature Gate component.

    Raises:
        RuntimeError: If the Feature Gate component is not initialized.

    Returns:
        The Feature Gate component.
    """
    global _feature_gate
    if _feature_gate is None:
        raise RuntimeError("Feature Gate component not initialized")
    return _feature_gate
```

2024-03-07 15:18 UTC, safoinme commented on src/zenml/zen_server/utils.py
> +        _feature_gate = implementation_class()
```suggestion
    """Initialize the RBAC component."""
    global _feature_gate

    if (
        feature_gate_source
        := server_config().feature_gate_implementation_source
    ):
        implementation_class = source_utils.load_and_validate_class(
            feature_gate_source, expected_class=FeatureGateInterface
        )
        _feature_gate = implementation_class()
```

2024-03-07 18:21 UTC, bcdurak reviewed
I left a few comments, otherwise, everything looks good. Would still love to get your opinion on a few things when you have time though.

2024-03-07 18:21 UTC, bcdurak commented on src/zenml/zen_server/feature_gate/endpoint_utils.py
> +def report_decrement(resource_type: ResourceType) -> None:
Is this function unused?

2024-03-11 15:37 UTC, AlexejPenner commented on src/zenml/zen_server/feature_gate/endpoint_utils.py
> +def report_decrement(resource_type: ResourceType) -> None:
yes

2024-03-11 17:05 UTC, AlexejPenner commented on src/zenml/zen_server/utils.py
> +        _feature_gate = implementation_class()
sorry I don't understand this :D

2024-03-11 17:05 UTC, AlexejPenner commented on src/zenml/zen_server/utils.py
> +    return _feature_gate
sorry I don't understand this :D

2024-03-11 17:06 UTC, AlexejPenner commented on src/zenml/zen_server/rbac/endpoint_utils.py
Nope, was like that before, good catch

2024-03-13 11:09 UTC, AlexejPenner commented on src/zenml/constants.py
> +        except (TypeError, json.JSONDecodeError):
fixed it

2024-03-13 12:01 UTC, stefannica requested changes
Barely skimmed it, but it looks mostly alright from what I can see. The unrelated formatting changes are a pain though, I could live without them.

2024-03-13 12:01 UTC, stefannica commented on src/zenml/zen_server/cloud_utils.py
> +                    "reach out to us."
```suggestion
                    "upgrade your subscription or "
                    "reach out to the ZenML team."
```

2024-03-13 17:04 UTC, AlexejPenner commented on src/zenml/constants.py
> +)
with this you simply mean naming of the env var? or also how its loaded in other places?

2024-03-13 17:16 UTC, AlexejPenner commented on src/zenml/zen_server/cloud_utils.py
> +                env_config[k[len(ZENML_CLOUD_RBAC_ENV_PREFIX) :].lower()] = v
phew, changing this one seems like a headache. Doesn't this then mean we need migrations in spacelift and changes to the infra repo

2024-03-22 15:22 UTC, bcdurak approved these changes
🦭

2024-03-25 11:40 UTC, stefannica approved these changes

2024-03-26 10:04 UTC, merged