Update docs with warning about pickle materializer insecurity
zenml-io/zenml pull request #2561
Opened 2024-03-22 14:45 UTC by avishniakov

## Describe changes
I updated the docs with a proper warning to address https://www.redpacketsecurity.com/zenml-file-upload-cve-2024-28424/

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-03-22 14:51 UTC, strickvl requested changes

2024-03-22 14:51 UTC, strickvl commented on docs/book/user-guide/advanced-guide/data-management/artifact-versioning.md
> +Moreover, usage of the `CloudpickleMaterializer` could allow to upload of any kind of an object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerab
```suggestion
Moreover, using the `CloudpickleMaterializer` could allow users to upload of any kind of object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerable system.
```

2024-03-22 14:51 UTC, strickvl commented on docs/book/user-guide/advanced-guide/data-management/artifact-versioning.md
> +Moreover, usage of the `CloudpickleMaterializer` could allow to upload of any kind of an object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerab
and same below

2024-03-22 15:20 UTC, avishniakov commented on docs/book/user-guide/advanced-guide/data-management/handle-custom-data-types.md
> +Moreover, usage of the `CloudpickleMaterializer` could allow to upload of any kind of an object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerab
```suggestion
Moreover, using the `CloudpickleMaterializer` could allow users to upload of any kind of object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerable system.
```

2024-03-22 15:20 UTC, avishniakov commented on docs/book/user-guide/advanced-guide/pipelining-features/managing-steps.md
> +Moreover, usage of the `CloudpickleMaterializer` could allow to upload of any kind of an object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerab
```suggestion
Moreover, using the `CloudpickleMaterializer` could allow users to upload of any kind of object. This could be exploited to upload a malicious file, which could execute arbitrary code on the vulnerable system.
```

2024-03-22 15:22 UTC, strickvl approved these changes

2024-03-25 09:34 UTC, stefannica approved these changes

2024-03-25 09:35 UTC, merged