Completing and refining the CLI documentation
zenml-io/zenml pull request #2605
Opened 2024-04-10 13:11 UTC by bcdurak

## Describe changes
I have completed the missing parts of our CLI documentation.

### Remaining TODOs
- [x] The following commands are still completely missing from the docs:
  - [x] tags
  - [x] service-accounts
  - [x] authorized-device
- [x] Add docs links for all types
- [x] Fix the TOC including titles

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [X] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Other (add details above)

2024-04-10 13:15 UTC, strickvl commented
@coberabbitai review

2024-04-10 13:17 UTC, strickvl commented
@coderabbitai review

2024-04-11 09:57 UTC, strickvl requested changes

2024-04-11 12:47 UTC, bcdurak commented on src/zenml/cli/__init__.py
> +token instead.
fixed it.

2024-04-11 12:48 UTC, bcdurak commented on src/zenml/cli/__init__.py
> +can fetch the list of resource it has access to:
fixed it.

2024-04-11 13:14 UTC, strickvl requested changes

2024-04-11 15:53 UTC, bcdurak commented on src/zenml/cli/__init__.py
> +In ZenML, [the artifact store](https://docs.zenml.io/stacks-and-components/component-guide/artifact-stores)
True. However, I have been involved in such cases before. In most cases we do a complete sweep over the database and replace all occurrences of documentation links accordingly. This should normally not be an issue.

2024-04-11 15:57 UTC, strickvl approved these changes

2024-04-11 15:58 UTC, strickvl approved these changes

2024-04-15 07:04 UTC, merged