Make a clear separation between server and dashboard API in the server configuration
zenml-io/zenml pull request #2722
Opened 2024-05-23 18:00 UTC by stefannica

## Describe changes
There was some confusion and overlap between the `base_url` and `dashboard_url` ZenML server configuration values. This PR makes a clear separation between these configurations and includes them both in the server info and using them properly throughout:

* `server_url` replaces `base_url` - this is where the ZenML server itself is running / served.
* `dashboard_url` - this is where the ZenML dashboard is served. Can be different than `server_url`

Both values will always be set for ZenML Cloud tenants. Neither needs to be set for self-hosted servers.

## Side-changes

* change to the authorized device web login workflow code to use the dashboard URL instead of the server URL
* a change to the script used to install ZenML in a development environment is made to remove the installation of system-wide packages. Needed to install ZenML in a local python environment.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-05-23 21:21 UTC, schustmi requested changes

2024-05-23 21:21 UTC, schustmi commented on src/zenml/cli/web_login.py
> +    breakpoint()
⚠️

2024-05-24 07:34 UTC, stefannica commented on src/zenml/cli/web_login.py
> +    breakpoint()
zoink !

2024-05-24 08:20 UTC, schustmi approved these changes

2024-05-24 08:22 UTC, strickvl approved these changes

2024-05-24 11:51 UTC, merged