[WIP] Accelerate runner helper method
zenml-io/zenml pull request #2746
Opened 2024-06-04 10:38 UTC by avishniakov

## Describe changes
WIP

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-06-05 10:52 UTC, avishniakov commented
@strickvl , I can see that the docs for the `finetuning-llms` are not quite ready. Shall I wait for you or how to proceed best to documents these changes?

2024-06-05 10:59 UTC, strickvl commented
> @strickvl , I can see that the docs for the `finetuning-llms` are not quite ready. Shall I wait for you or how to proceed best to document these changes?

Could you maybe make changes directly on the `feature/gro-1047-docs` branch directly @avishniakov and I'll touch them up. You can see I added a short section at the bottom of `docs/book/how-to/training-with-gpus/training-with-gpus.md` page. Or just send something to me in Discord and I'll add it. I couldn't find/think of the good way to document this with code examples, but probably you're in a better place to do so.

2024-06-05 11:11 UTC, strickvl requested changes
Just one tiny comment otherwise looks good to me. Is there any testing we can add for the function utils? Also wondering if we should have an e2e test script which runs a simple (CPU-backed) pipeline in CI but using `run_with_accelerate`? I'm a bit worried by how quickly HF things can break, esp with something like `accelerate` so I'd like to get advance failure notice of API changes that way if possible.

2024-06-05 11:11 UTC, strickvl commented on src/zenml/utils/cuda_utils.py
> +            "If this is intended, please, explicitly pass `force=True`."
```suggestion
            "If this is intended, please explicitly pass `force=True`."
```

2024-06-13 15:58 UTC, strickvl approved these changes
Thanks for adding the tests. This LGTM now, providing you get the tests passing (there's a security one failing atm e.g.)

2024-06-17 16:53 UTC, avishniakov commented
@bcdurak, as discussed this one is ready to be merged, but can give more work to the pydantic merge. LMK, when can I merge it?

2024-06-18 11:36 UTC, merged