Better error message sagemaker, better documentation server env vars
zenml-io/zenml pull request #2885
Opened 2024-07-26 14:25 UTC by AlexejPenner

## Describe changes

When starting long running pipelines on sagemaker with the orchestrator configured to be synchronous, the error message was a bit cryptic. The new error message should instruct the user in what to do to avoid hitting it again.

The JWT_SECRET_KEY was not accessible anywhere in the docs.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-07-26 14:28 UTC, htahir1 approved these changes

2024-07-26 14:29 UTC, schustmi requested changes

2024-07-26 14:29 UTC, schustmi commented on src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
> +                    "`zenml orchestrator update <ORCHESTRATOR-NAME> --synchronous=False`"
Maybe `self.name` to have it concrete?

2024-07-26 14:29 UTC, schustmi commented on src/zenml/config/server_config.py
> +    The value of `$ZENML_SERVER_DEPLOYMENT_TYPE` will be extracted to deployment_type.
```suggestion
    The value of the `ZENML_SERVER_DEPLOYMENT_TYPE` environment variable will be extracted to deployment_type.
```

2024-07-29 07:09 UTC, schustmi approved these changes

2024-07-29 10:56 UTC, htahir1 approved these changes

2024-07-29 11:00 UTC, stefannica commented on docs/book/getting-started/deploying-zenml/deploy-with-docker.md
> +* **ZENML\_SERVER\_JWT\_SECRET\_KEY**: If you want to make sure your session tokens remain valid when spinning servers down and up again, a constant JWT secret key should be set. Feel free to choose
This is already documented a bit further down in the `Advanced server configuration options` section

2024-07-29 11:29 UTC, merged