Bump mlflow to 2.15.0
zenml-io/zenml pull request #2896
Opened 2024-07-31 09:08 UTC by christianversloot

## Describe changes
This PR bumps `mlflow` to its most recent version, `2.15.0`. I ran our test pipeline using `zenml==0.63.0` against `mlflow==2.15.0` and it succeeded:

![image](https://github.com/user-attachments/assets/331d392f-4704-4286-ab0d-35ed918555b6)
![image](https://github.com/user-attachments/assets/92846e9c-7caf-4256-ae7a-deac8710655b)

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [x] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

2024-08-06 12:50 UTC, avishniakov approved these changes
Thanks for contributing!

2024-08-06 14:23 UTC, christianversloot commented
@avishniakov No worries! Worthwhile to bump this PR to `2.15.1` before merging? https://github.com/mlflow/mlflow/releases/tag/v2.15.1

2024-08-07 06:48 UTC, htahir1 commented
@christianversloot go for it!

2024-08-07 07:11 UTC, avishniakov commented
@christianversloot , we had a chat internally, what about making `"mlflow>=2.1.1,<3",` and keeping it like that until something breaks?

2024-08-07 08:31 UTC, christianversloot commented
@avishniakov fine with me! Do your tests always work with the latest version? :)

2024-08-07 08:41 UTC, htahir1 requested changes
@christianversloot How bout trying this? We'll merge this if it works now

2024-08-07 08:41 UTC, htahir1 commented on src/zenml/integrations/mlflow/__init__.py
> +        "mlflow>=2.1.1,<=2.15.0",
```suggestion
        "mlflow>=2.1.1,<3",
```

2024-08-07 08:44 UTC, avishniakov commented
> @avishniakov fine with me! Do your tests always work with the latest version? :)

Yes, with the latest installable (a bit of a disclaimer if the latest-latest will not be installable due to the dependencies clash)

2024-08-07 09:39 UTC, christianversloot commented
@htahir1 @avishniakov Sure, good idea and nice that it works, I have a rather busy schedule today so will likely be able to adapt second part of the afternoon, if you need it before feel free to push a commit yourself :)

2024-08-08 07:06 UTC, htahir1 approved these changes

2024-08-08 07:06 UTC, merged