Linking registered models in MLflow with the corresponding MLflow run
zenml-io/zenml pull request #3020
Opened 2024-09-17 15:18 UTC by aiakide

## Describe changes

To link a registered model in MLflow with the corresponding MLflow run, the parameter `mlflow_run_id` must be included in the metadata argument of the `mlflow_register_model_step`. 

The MLflow run can be traced back to a ZenML pipeline run. This is not a necessary change. However, it is more convenient to have a reference to the MLflow run for the registered models as well, as this makes it possible to view parameters or metrics, for example.

I have adjusted the `mlflow_register_model_step` so that the `mlflow_run_id` is added by default if it is not already present in the metadata. 

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-09-18 09:48 UTC, schustmi requested changes

2024-09-18 09:48 UTC, schustmi commented on src/zenml/integrations/mlflow/steps/mlflow_registry.py
> +    if metadata.model_extra and "mlflow_run_id" in metadata.model_extra:
I'm a little confused by this change, can you explain the intended behaviour of this code?

To me it seems like:
- We first check whether the `mlflow_run_id` exists in the `model_extra` dict
- If it doesn't exist, we do nothing. Why don't we add the key in this case?
- If it does exist, we have another `if` condition, but both the `if` and `else` branch do exactly the same thing: They overwrite the key with the mlflow run id.

It seems like both the `if` and `else` condition do the same thing: Overwrite `mlflow_run_id` in the `model_extra` dict, no matter if it's `None` or not.

And why do we need the actual check ahead if the key even exists and not just always set it?

2024-09-18 11:22 UTC, schustmi approved these changes

2024-09-18 11:22 UTC, schustmi commented on src/zenml/integrations/mlflow/steps/mlflow_registry.py
> +    if metadata.model_extra and "mlflow_run_id" in metadata.model_extra:
Yep looks good now!

2024-09-24 12:43 UTC, safoinme approved these changes

2024-09-24 12:44 UTC, merged