Add UUID_VERSION constant in uuid_utils.py
zenml-io/zenml pull request #3104
Opened 2024-10-19 17:11 UTC by ablazejuk

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-10-19 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zenml-io/zenml?pullRequest=3104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zenml-io/zenml?pullRequest=3104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zenml-io/zenml?pullRequest=3104) it.</sub>

2024-10-21 07:32 UTC, schustmi requested changes
@ablazejuk Can you name this `DEFAULT_UUID_VERSION` and also apply this to the other places where we call `UUID(..., version=...)` in this file?

2024-10-26 23:04 UTC, ablazejuk commented
> @ablazejuk Can you name this `DEFAULT_UUID_VERSION` and also apply this to the other places where we call `UUID(..., version=...)` in this file?

Done

2024-10-27 09:28 UTC, schustmi approved these changes

2024-10-28 09:51 UTC, schustmi commented
@ablazejuk The PR is still failing the linting. Can you run `bash scripts/format.sh` to resolve this please

2024-11-03 05:49 UTC, closed without merging