Terraform best practices
zenml-io/zenml pull request #3131
Opened 2024-10-23 13:19 UTC by htahir1

## Describe changes
Preview: https://zenml-io.gitbook.io/hamza-test/how-to/infrastructure-deployment/infrastructure-as-code/terraform-stack-management  and https://zenml-io.gitbook.io/hamza-test/how-to/infrastructure-deployment/infrastructure-as-code/best-practices

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] If my changes require changes to the dashboard, these changes are communicated/requested.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-11-04 12:59 UTC, strickvl requested changes
Looks pretty good! just some small nits

2024-11-04 12:59 UTC, strickvl commented on docs/book/how-to/infrastructure-deployment/infrastructure-as-code/best-practices.md
> +- Use workspaces for different environments
link to workspace docs, or did you mean TF workspaces?

2024-11-04 12:59 UTC, strickvl commented on docs/book/how-to/infrastructure-deployment/infrastructure-as-code/best-practices.md
> +- Keep registration state with the ML operations team
what does this mean?

2024-11-04 12:59 UTC, strickvl commented on docs/book/how-to/infrastructure-deployment/infrastructure-as-code/terraform-stack-management.md
> +You can learn more about how to generate a ZENML_API_KEY via service accounts
```suggestion
You can learn more about how to generate a 1ZENML_API_KEY` via service accounts
```

2024-11-04 14:47 UTC, strickvl commented on docs/book/how-to/infrastructure-deployment/infrastructure-as-code/terraform-stack-management.md
> +You can learn more about how to generate a 1ZENML_API_KEY` via service accounts
```suggestion
You can learn more about how to generate a `ZENML_API_KEY` via service accounts
```

2024-11-04 14:51 UTC, strickvl approved these changes

2024-11-11 09:39 UTC, stefannica approved these changes

2024-11-11 09:43 UTC, merged