Finetuning guide
zenml-io/zenml pull request #3157
Opened 2024-10-30 17:36 UTC by strickvl

Draft of documentation / guide around LLM finetuning.

Gitbook preview [here](https://app.gitbook.com/o/-MCl1Hlw9oU4xibZ-ymf/s/x9UKvIZt4T0daMw6mLMM/user-guide/llmops-guide/finetuning-llms/finetuning-100-loc).

## Remaining work

- [ ] more diagrams
- [ ] complete the deployment writeup (when #3032 is merged in)

2024-10-31 10:56 UTC, htahir1 requested changes
Alright i read it again. I think its great. But I have some feedback:

* There are lots of lists in the text like "Here is a list: here is an explanation" -> Id format this with the first part being in bold "**Here is a list**: here is an explanation"
* This is again a pet peeve but bullet points , should they begin with a capital or small letter?...
* For me the chapter that sort of doesn't "fit" well into the guide is "Starter choices with fine-tuning". I'm not quite sure whether its the lack of link outs or the lack of code in there that makes it just feel like I have a lot of reading to do before I get to the action.. maybe there is a way to condense it into a visual element or maybe tell the story in a code-centric way? Or give more examples as to the choices available? 
* Finetuning with Accelerate doesn't point out that we have an integration with a decorator... that is what I expected here tbh
* I expected a link from the new evaluation section to the old RAG evaluation section but I found only "Please note that the approach taken for these evaluations is similar to that used and [showcased in the RAG guide](https://github.com/o/-MCl1Hlw9oU4xibZ-ymf/s/x9UKvIZt4T0daMw6mLMM/user-guide/llmops-guide/evaluation)." .. Maybe there is a way to pick up the story from there? What is actually different from what was said before? There might be a shortcut by making a link back
* The deployment chapter is missing a code snippet from our VLLM deployer by @dudeperf3ct :-) Id love to get that in there, even if it isn't released yet.

2024-11-06 10:00 UTC, htahir1 requested changes
Feedback:

- Looks like a lot of files have been deleted - would it make sense to add redirects for these?
- Other than that and the comments this looks SUPER amazing and solid. Great work!!!

2024-11-06 10:00 UTC, htahir1 commented on docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms.md
This seems underdeveloped. Also dont we call this README.md usually?

2024-11-06 10:00 UTC, htahir1 commented on docs/book/user-guide/llmops-guide/finetuning-llms/why-and-when-to-finetune-llms.md
> +- [Retrieval-Augmented Generation (RAG)](../rag-with-zenml/understanding-rag.md): For many use cases involving specific knowledge bases, RAG can be more effective and easier to maintain than finetuni
broken link

2024-11-06 10:00 UTC, htahir1 commented on docs/book/user-guide/llmops-guide/finetuning-llms/getting-started-with-finetuning.md
the name of the file can be a bit more aligned with the content

2024-11-06 10:00 UTC, htahir1 commented on docs/book/user-guide/llmops-guide/finetuning-llms/getting-started-with-finetuning.md
> +### 🎯 Good vs Not-So-Good Use Cases
i love this, it deserves a blog post on its own

2024-11-06 10:00 UTC, htahir1 commented on docs/book/user-guide/llmops-guide/finetuning-llms/next-steps.md
IMO we can link to papers / books or other resources that might be useful here

2024-11-06 12:02 UTC, strickvl commented
@htahir1 the deleted files were actually duplicate docs which weren't linked anywhere, so no need to link. they weren't in our TOC to start with.

2024-11-06 12:35 UTC, strickvl commented on docs/book/user-guide/llmops-guide/finetuning-llms/getting-started-with-finetuning.md
done

2024-11-06 12:45 UTC, htahir1 approved these changes
Amazing! LGTM!

2024-11-06 13:10 UTC, wjayesh commented on docs/book/user-guide/llmops-guide/finetuning-llms/why-and-when-to-finetune-llms.md
> +## When makes sense to finetune an LLM?
```suggestion
## When does it make sense to finetune an LLM?
```

2024-11-06 13:14 UTC, wjayesh approved these changes

2024-11-06 13:15 UTC, merged