Implement cross-site external authentication protected by CSRF tokens
zenml-io/zenml pull request #3264
Opened 2024-12-13 20:00 UTC by stefannica

## Describe changes

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.
- [ ] I have based my new branch on `develop` and the open PR is targeting `develop`. If your branch wasn't based on develop read [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/zenml/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).
- [ ] **IMPORTANT**: I made sure that my changes are reflected properly in the following resources:
  - [ ] [ZenML Docs](https://docs.zenml.io)
  - [ ] Dashboard: Needs to be communicated to the frontend team.
  - [ ] Templates: Might need adjustments (that are not reflected in the template tests) in case of non-breaking changes and deprecations.
  - [ ] [Projects](https://github.com/zenml-io/zenml-projects): Depending on the version dependencies, different projects might get affected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2024-12-27 13:56 UTC, stefannica commented on src/zenml/zen_server/routers/auth_endpoints.py
> -        )
TODO: the dependency on the external cookie can be completely removed here ONLY if the dashboard always uses the tenant authorization flow, even for same-site tenants.

2025-01-03 13:35 UTC, schustmi requested changes

2025-01-03 13:35 UTC, schustmi commented on src/zenml/config/server_config.py
> +                "zenml.zen_server.rbac.zenml_cloud_rbac.ZenMLCloudRBAC"
These files are not available for servers deployed with the OSS Docker image, which might lead to errors if the environment variables are configured.

2025-01-03 13:35 UTC, schustmi commented on src/zenml/config/server_config.py
> +class ServerProConfiguration(BaseModel):
Maybe i'm still missing some details, but all these environment variables need to be set by users when they decide they want to enroll a server? Or how is the actual user flow for enrollment supposed to look like?

2025-01-11 14:43 UTC, stefannica commented on src/zenml/config/server_config.py
> +class ServerProConfiguration(BaseModel):
I documented the enrollment flow here: https://www.notion.so/zenml/ZenML-Pro-On-Prem-new-173f8dff25388001a9f4e4f093da1b84

For now, the users need to set these variables when they decide to enroll a server. In the future, we'll implement dynamic configuration for all these (we'll basically store these in the database and have an endpoint to update them), which will allow users to enroll tenants without re-deploying them.

2025-01-11 14:44 UTC, stefannica commented on src/zenml/config/server_config.py
> +                "zenml.zen_server.rbac.zenml_cloud_rbac.ZenMLCloudRBAC"
I'm pretty sure they are available with the OSS code.

2025-01-11 14:50 UTC, stefannica commented on src/zenml/constants.py
> +DEFAULT_REPORTABLE_RESOURCES = ["pipeline", "pipeline_run", "model"]
This is a server configuration setting, but it was modeled here instead of being part of the `ServerConfiguration` class, like all the others. I merely moved it there. Not a necessary change, but a cosmetic one.

2025-01-11 15:05 UTC, stefannica commented on src/zenml/zen_stores/migrations/versions/1cb6477f72d6_move_artifact_save_type.py
> +    op.execute(
Yes, probably. I merged develop back in and removed these unnecessary changes.

2025-01-14 13:39 UTC, schustmi commented on src/zenml/config/server_config.py
> +                "zenml.zen_server.rbac.zenml_cloud_rbac.ZenMLCloudRBAC"
Yes you're right, I was thinking of the `workload_manager`, which you left as a configuration option passed by the cloudapi when deploying managed tenants.

2025-01-14 13:47 UTC, schustmi approved these changes

2025-01-15 09:33 UTC, merged