Implement azure artifact store and fileio plugin
zenml-io/zenml pull request #388
Opened 2022-02-03 17:04 UTC by schustmi

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
- Implement azure artifact store and fileio plugin

2022-02-03 18:28 UTC, htahir1 reviewed
Nice what a cool addition!

2022-02-03 18:28 UTC, htahir1 commented on src/zenml/integrations/azure/__init__.py
> +    REQUIREMENTS = ["adlfs"]
Maybe we can start pinning these?

2022-02-04 08:59 UTC, wjayesh requested changes

2022-02-04 08:59 UTC, wjayesh commented on src/zenml/integrations/azure/__init__.py
> +and an `io` module to handle file operations on Azure Data Lakes .
We only added support for Azure Blob Storage, as of now.

2022-02-04 08:59 UTC, wjayesh commented on src/zenml/integrations/azure/io/azure_plugin.py
> +    To authenticate with an Azure Data Lake storage, make sure to set a
Small correction from Data Lake to Blob Storage

2022-02-07 11:36 UTC, wjayesh approved these changes

2022-02-07 11:40 UTC, merged