Add docstring checks to `pre-commit` script
zenml-io/zenml pull request #481
Opened 2022-03-25 20:25 UTC by strickvl

I added a `pre-commit` check that ensures all methods contain correct docstrings as per our formatting and that arguments in the method/function signatures match what are specified in the docstring.

I implemented several modules to start with as you can see in the files, but merging `develop` added in a bunch more failing code so you'll see that the darglint / pydocstyle checks are only running for two modules. I will add smaller scoped PRs over the coming weeks to cover the rest.

The docstring checks now run as part of the `lint` script, but I added a separate `docstring.sh` script for the purpose of working on the specific task of fixing docstrings (so that you don't have to also run things like `mypy` that take extra time).

I'll also circulate a Notion document so that the implications / decisions around this will be clear.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-03-28 11:58 UTC, htahir1 requested changes
Cool. But if we are using this tool, we need a way to use it outside of just the pre-commit. We need it in the GitHub actions via a `scripts/docstrings-check.sh` or something. We can then also use that script locally without pre-commit. That means we need to add it to the `pyproject.toml`. So its a bit more work :-)

2022-03-28 12:37 UTC, strickvl commented
@htahir1 Yes I'll add it to the script as well. This was very much a draft PR for the moment. Our codebase has hundreds of methods that need fixing, so I'll work on this slowly on the side as it's not such a high-priority thing needing an immediate fix.

2022-05-30 10:47 UTC, schustmi approved these changes

2022-05-30 15:57 UTC, htahir1 approved these changes

2022-05-30 15:57 UTC, merged