Update Weights and Biases Integration
zenml-io/zenml pull request #486
Opened 2022-03-28 18:56 UTC by soumik12345

## Describe changes
Updating [Weights and Biases](https://wandb.ai/) Integration.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes
New feature (non-breaking change which adds functionality)

2022-03-28 18:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zenml-io/zenml?pullRequest=486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zenml-io/zenml?pullRequest=486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zenml-io/zenml?pullRequest=486) it.</sub>

2022-03-29 13:26 UTC, htahir1 commented
@soumik12345 Would you mind signing the CLA? https://cla-assistant.io/zenml-io/zenml?pullRequest=486

2022-04-06 11:18 UTC, soumik12345 commented
> @soumik12345 Would you mind signing the CLA? https://cla-assistant.io/zenml-io/zenml?pullRequest=486

Hi @htahir1 , I have signed the CLA

2022-04-07 08:12 UTC, htahir1 requested changes
Thanks for signing the CLA! Just one small comment and then we can merge and move forward!

2022-04-07 08:12 UTC, htahir1 commented on pyproject.toml
> +wandb = "^0.12.12"
Hey @soumik12345 , we dont usually add dependencies in our core dependency project.toml. I would ask you to remove changes to the pyproject.toml and put them instead in `src/zenml/ntegrations/wandb/__init__.py`. We have another way of controlling these dependencies

2022-04-14 07:49 UTC, merged

2022-04-14 09:51 UTC, htahir1 commented
Thank you so much for the help!