Added support for scipy sparse matrices
zenml-io/zenml pull request #534
Opened 2022-04-22 21:44 UTC by avramdj

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-04-24 22:01 UTC, AlexejPenner commented
@avramdj Thanks so much for your submission. Being able to materialize sparse matrices natively is definitely a win for the ZenML community.

As you can see in our Github Actions we are running into a small issue though regarding the scipy installation. Currently Scipy is not a ZenML dependency and as such the code for Scipy Materialization should not be within the core part of our code. Instead you will need to create a Scipy integration and move the materializer there. 

Have a look at our huggingface integration that was recently contributed:

2022-04-25 12:06 UTC, schustmi requested changes
Thanks a lot @avramdj ! @AlexejPenner already outlined the general way to make this an integration so I'll keep my feedback to two small typos

2022-04-25 12:06 UTC, schustmi commented on src/zenml/materializers/sparse_materializer.py
> +        """Writes a spmatrix to the artifact store as a parquet file.
```suggestion
        """Writes a spmatrix to the artifact store as a npz file.
```

2022-04-28 13:53 UTC, avramdj commented
Hey, thanks for the feedback. I've moved it into a new integration (accidentally commited from my work profile but that's still me). I'm not very experienced with contributing to open source so I'm glad you guys can keep me in check :). Does this look better?

Also, I have a question relating to how integrations work for packages that depend on each other, like `sklearn` in this example. Should the installation of the `sklearn` integration induce the installation of the `scipy` integration?

Thanks.

2022-04-28 14:56 UTC, AlexejPenner requested changes
That makes it all the more exciting to have you contributing. 

Yeah this looks good. In order to run our gh actions on it you will have to merge our newly released develop branch into yours and resolve all conflicts, before pushing again.

I just found a very tiny improvement :)

If you are interested and have the time for it, you could also add a minimal example of code running with this materializer to our examples. This will help our users quickly see how to use this materializer and it will enable us to add this example into our suite of integration tests. 
If you are interested in adding this feel free to check out our guide on [how to write an example](https://github.com/zenml-io/zenml/tree/feature/ENG-634-beautify-examples/examples/add_your_own) that we are currently working on.

2022-04-28 14:56 UTC, AlexejPenner commented on src/zenml/integrations/__init__.py
> +from zenml.integrations.scipy import ScipyIntegration
```suggestion
from zenml.integrations.scipy import ScipyIntegration  # noqa
```

I assume we'll want to skip linting here too.

2022-04-28 15:01 UTC, AlexejPenner commented
> Also, I have a question relating to how integrations work for packages that depend on each other, like `sklearn` in this example. Should the installation of the `sklearn` integration induce the installation of the `scipy` integration?
>

You won't have to do anything special regarding this. When the user installs sklearn, the appropriate scipy version will be installed. ZenML will detect that scipy is installed and the scipy integration will be considered active.

2022-04-28 17:32 UTC, avramdj commented
The `README.md` states I should keep the example as simple and straightforward as possible while avoiding unnecessary dependencies. This maybe defeats the purpose a bit since the most common use case of this materializer is within `sklearn` text processing pipelines. Right now it's really just bare-bones.

2022-04-28 17:40 UTC, AlexejPenner commented
> The `README.md` states I should keep the example as simple and straightforward as possible while avoiding unnecessary dependencies. This maybe defeats the purpose a bit since the most common use case of this materializer is within `sklearn` text processing pipelines. Right now it's really just bare-bones.

I've had a look at your implementation. I think you are right. Maybe I should adjust the language of the guide a bit. I think it would be alright to put it into the correct context here by including it in such a text processing pipeline. Feel free to propose something. What I meant with simple was more along the line of 'the model it produces doesn't have to be anything special' and the required data shouldn't be too large. The purpose of the examples is to quickly show how to use the integration in its respective context.

2022-04-28 22:40 UTC, avramdj commented
Hope this is okay. The only thing I wish i could have avoided is storing the `csv` directly in the example, but I thought it was okay since I've seen it in other examples. Also, I hardcoded the hyperparams instead of making a step config, just so the code is more straightforward and less overwhelming for new users, I don't think it's something particularly interesting in this case but I can change it if you want.

2022-05-01 14:16 UTC, AlexejPenner reviewed
I have left two small comments regarding the csv file. 

In the meantime I'll try figuring out if we can host the csv files somewhere to make the data loader step import the files instead of loading them from your local filesystem.

2022-05-01 14:16 UTC, AlexejPenner commented on examples/scipy/README.md
> +We train a simple linear model to classify text based on sentiment.
As you have included that dataset as a csv file it would be good (and maybe even required by its licence) to include areference to the dataset here.

2022-05-01 14:16 UTC, AlexejPenner commented on examples/scipy/README.md
> +The text is represented via a sparse [bag of words](https://en.wikipedia.org/wiki/Bag-of-words_model) vector.
Additionally it could be good to have a small example here:

Input data -> bag of words vector

2022-05-03 08:46 UTC, schustmi approved these changes

2022-05-03 08:50 UTC, AlexejPenner commented
Good to go from my side as well :) - Thanks so much for your contribution. We'd love to see more of your code in the future :wink:

2022-05-03 08:50 UTC, AlexejPenner approved these changes

2022-05-03 08:57 UTC, avramdj commented
Thank you, I will try making my future PRs smoother :)

2022-05-03 09:26 UTC, merged