Add container registry types
zenml-io/zenml pull request #551
Opened 2022-04-29 16:41 UTC by htahir1

## Describe changes
According to our discussion, I have added container registry types into the base src of ZenML, in order that we can validate container registries in a nice case-by-case basis.

I am looking for either @schustmi or @stefannica to take over this branch at this point. I feel like you might take it to completion easier, and I have done all the copy paste work here. If you guys are busy, also happy to take this into completion. Some feedback here would be welcome in this case :100: 

# TODO:

- [ ] Update docs (we can do this in @AlexejPenner branch)
- [ ] Write tests

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-05-03 08:19 UTC, schustmi requested changes
Very nice change that aligns the container registries with all the remaining stack components. I left a few minor comments, and will add two more general requests here:
- I think all container registries would benefit from receiving additional validations with example URLs similar to the one you wrote for AWS
- I'm guessing we can/should update some docs here to use the new container registry flavors? While using the default one would still work, I think our examples (e.g. running on EKS kubeflow) would benefit from the additional validation that it's an ECR registry

2022-05-03 08:19 UTC, schustmi commented on src/zenml/enums.py
> +class ContainerRegistry(StrEnum):
I think in all other cases we handle these flavors as simple string constants now, but I can see the point of having them as an enum with that many zenml core implementations. I'd still vote for changing the enum name to `ContainerRegistryFlavor` or similar

2022-05-03 08:19 UTC, schustmi commented on src/zenml/enums.py
> +    """Types of container registries."""
```suggestion
    """Flavors of container registries."""
```

2022-05-03 08:19 UTC, schustmi commented on src/zenml/container_registries/github_container_registry.py
> +    """Class for ECR Container Registry.
```suggestion
    """Class for Github Container Registry.
```

2022-05-03 08:19 UTC, schustmi commented on src/zenml/container_registries/aws_container_registry.py
> +    def validate_aws_uri(cls, uri: str) -> None:
I really like the validation with the error message giving a concrete example! One thing that might be worth considering is allowing a trailing slash and simply removing it? And probably we can even have a regex that checks if the uri ends with `amazonaws.com`, but I'm not familiar enough with the potential urls they might have

2022-05-06 15:06 UTC, stefannica approved these changes

2022-05-06 16:13 UTC, merged