Improve error message for missing return type annotations of `@step` functions
zenml-io/zenml pull request #584
Opened 2022-05-11 16:35 UTC by fa9r

## Describe changes
I added an error message for when the return type annotation of an `@step` function is missing.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [x] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [x] I have added tests to cover my changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-05-11 16:48 UTC, htahir1 requested changes
Great error message! Just small nits

2022-05-11 16:48 UTC, htahir1 commented on src/zenml/steps/base_step.py
> +                f"and outputs."
```suggestion
                f"and outputs. If your step returns nothing, please annotate it with `-> None`."
```

2022-05-11 16:48 UTC, htahir1 commented on src/zenml/steps/step_decorator.py
> +        StepInterfaceError: raises an error if _func is not type annotated.
```suggestion        
```

2022-05-11 16:48 UTC, htahir1 commented on src/zenml/steps/step_decorator.py
> +            StepInterfaceError: raises an error if _func is not type annotated.
```suggestion
```

2022-05-11 16:48 UTC, htahir1 commented on src/zenml/steps/step_decorator.py
> +        StepInterfaceError: raises an error if _func is not type annotated.
```suggestion
```

2022-05-12 07:38 UTC, schustmi approved these changes

2022-05-12 10:25 UTC, htahir1 approved these changes

2022-05-12 10:30 UTC, merged