Feature/change zen service to zen server
zenml-io/zenml pull request #585
Opened 2022-05-12 09:08 UTC by safoinme

## Describe changes

- Change the name "Zen Service/ZenService" to "Zen Server/ZenServer". _**ENG-875**_
- Remove import and handle registration of the ZenServer "ZenService" more gracefully. _**ENG-863**_

## Pre-requisites
Please ensure you have done the following:
- [X] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Other (add details above)

2022-05-12 11:17 UTC, stefannica requested changes
Found a few typos, but looks good otherwise.

2022-05-12 11:17 UTC, stefannica commented on src/zenml/cli/config.py
> +    help="The username that is used to authenticate with the ZenServe. This "
```suggestion
    help="The username that is used to authenticate with the ZenServer. This "
```

2022-05-12 11:17 UTC, stefannica commented on src/zenml/cli/server.py
> +@server.command("explain", help="Explain the the concept of the Zen Server.")
```suggestion
@server.command("explain", help="Explain the Zen Server concept.")
```

2022-05-12 11:17 UTC, stefannica commented on src/zenml/cli/server.py
> +    """Explain the concept of the Zen Server."""
```suggestion
    """Explain the Zen Server concept."""
```

2022-05-12 11:17 UTC, stefannica commented on src/zenml/zen_server/zen_server.py
> +        """Get the URI where the service responisble for Zen Server is running.
```suggestion
        """Get the URI where the service responsible for Zen Server is running.
```

2022-05-13 08:59 UTC, strickvl requested changes
Some small nits in here. I think you should make sure that changes happening in the various other docs branches also reflect this naming change (or maybe just message the people working on that to make sure they're aware). Otherwise looks good to me!

2022-05-13 08:59 UTC, strickvl commented on src/zenml/cli/server.py
>      """ZenML server."""
Should this be ZenServer?

2022-05-13 08:59 UTC, strickvl commented on src/zenml/cli/server.py
>      """ZenML server."""
I guess this question applies to any other place where we talk about 'ZenML server'.

2022-05-13 08:59 UTC, strickvl commented on src/zenml/cli/server.py
> +    """Provisions resources for the zen server."""
```suggestion
    """Provisions resources for the ZenServer."""
```

2022-05-13 08:59 UTC, strickvl commented on src/zenml/zen_server/zen_server.py
> +        zen_server_uri_path: URI path for the zenml service
```suggestion
        zen_server_uri_path: URI path for the ZenServer
```

?

2022-05-13 08:59 UTC, strickvl commented on src/zenml/zen_server/zen_server.py
> +        port: Port at which the service responisble for ZenServer is running
```suggestion
        port: Port at which the service responsible for the ZenServer is running
```

2022-05-13 08:59 UTC, strickvl commented on src/zenml/zen_server/zen_server.py
> +        """Get the URI where the service responsible for ZenServer is running.
```suggestion
        """Get the URI where the service responsible for the ZenServer is running.
```

2022-05-13 08:59 UTC, strickvl commented on tests/unit/zen_server/test_zen_server.py
> +    """Spin up a zen server to do tests on."""
```suggestion
    """Spin up a ZenServer for tests."""
```

2022-05-13 09:25 UTC, strickvl approved these changes
🙌

2022-05-13 16:00 UTC, merged