Fix some docs phrasings and headers
zenml-io/zenml pull request #670
Opened 2022-05-31 14:46 UTC by strickvl

...as mentioned in a livecoding session just now...

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-06-01 07:40 UTC, strickvl commented on docs/book/developer-guide/runtime-configuration.md
> +and don't wait to your actual step code. This is useful in the development phase.
```suggestion
and don't want to change your actual step code. This is useful in the development phase.
```

Possibly? The original phrasing was unclear for me.

2022-06-02 08:54 UTC, htahir1 requested changes
Great changes. Especially moving the run name section makes a lot of sense. Overall I would push to have the headline usage somewhat standardized across pages, i.e. where to use h1, h2, ... This still seems a bit inconsistent.

- Felix fromHamza's machine

2022-06-02 08:54 UTC, htahir1 commented on docs/book/introduction/core-concepts.md
> +  run your machine learning
```suggestion
  run your machine learning code
```

2022-06-02 08:54 UTC, htahir1 commented on docs/book/developer-guide/materializer.md
> +# Writing a custom materializer
IMO only the main headline should be h1 and I would use h2 for all subheaders within a page like this one. Might reformatting this whole file tho.

2022-06-02 12:55 UTC, htahir1 commented
I added @fa9r as a reviewer as you made this review from my PC :D. @AlexejPenner maybe also take a look?

2022-06-03 08:41 UTC, htahir1 commented
@AlexejPenner  and @fa9r please do take a look when you have time

2022-06-03 09:13 UTC, fa9r approved these changes
LGTM now :)

2022-06-03 09:30 UTC, AlexejPenner approved these changes
:rocket:

2022-06-03 19:50 UTC, merged