Docstring fixes for `entrypoints` and `experiment_trackers` modules
zenml-io/zenml pull request #672
Opened 2022-05-31 16:19 UTC by strickvl

I made the relevant fixes for the `entrypoints` and `experiment_trackers` modules, bringing the docstrings in line with our new style.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-05-31 17:03 UTC, fa9r requested changes
Several lines are >80 chars now and there is one change in _parse_arguments that seems odd. Otherwise looks good!

2022-05-31 17:03 UTC, fa9r commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +            A set of strings with all the options that are required when running.
> 80 chars

2022-05-31 17:03 UTC, fa9r commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +        """Gets all the options that are required when running an entrypoint with this configuration.
>80 chars

2022-05-31 17:03 UTC, fa9r commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +        """Runs setup code that needs to run before any user code is imported or the step is executed.
>80 chars

2022-05-31 17:03 UTC, fa9r commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +        """Custom options for this entrypoint configuration that are required in addition to the default ZenML ones.
>80 chars

2022-05-31 17:03 UTC, fa9r commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +"""Abstract base class for entrypoint configurations that run a single step."""
>80 chars

2022-06-01 08:09 UTC, strickvl commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +                        incorrect or one of the options is missing.
Some issue with `darglint`. I've fixed it by adding in an ignore comment for this error on this specific function.

2022-06-01 08:19 UTC, strickvl commented on src/zenml/entrypoints/step_entrypoint_configuration.py
> +"""Abstract base class for entrypoint configurations that run a single step."""
73 characters.

2022-06-01 09:34 UTC, htahir1 approved these changes

2022-06-02 03:49 UTC, merged