GitHub actions orchestrator example
zenml-io/zenml pull request #703
Opened 2022-06-13 15:10 UTC by schustmi

## Describe changes
I implemented/fixed _ to achieve _.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-06-13 15:20 UTC, strickvl requested changes

2022-06-13 15:20 UTC, strickvl commented on examples/github_actions_orchestration/README.md
> +* You'll also need to create a GitHub personal access token that allows you read/write GitHub secrets and push docker images to your GitHub container registry. To do so, please follow [this guide](ht
```suggestion
* You'll also need to create a GitHub personal access token that allows you read/write GitHub secrets and push Docker images to your GitHub container registry. To do so, please follow [this guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and make sure to assign your token the **repo** and **write:packages** scopes.
```

2022-06-13 15:20 UTC, strickvl commented on examples/github_actions_orchestration/README.md
> +# Login to the GitHub container registry so we can push the docker images required to run your ZenML pipeline.
```suggestion
# Login to the GitHub container registry so we can push the Docker images required to run your ZenML pipeline.
```

2022-06-13 15:20 UTC, strickvl commented on examples/github_actions_orchestration/README.md
> +# Register one of the following secrets depending on the flavor of artifact store that you've registered
```suggestion
# Register one of the following secrets depending on the flavor of artifact store that you've registered:
```

2022-06-13 15:20 UTC, strickvl commented on examples/github_actions_orchestration/README.md
> +That's it! If everything went as planned this pipeline should now be running in
```suggestion
That's it! If everything went as planned, this pipeline should now be running in
```

2022-06-13 15:30 UTC, strickvl approved these changes
Looks good to me, pending resolution of conflicts etc..

2022-06-13 15:40 UTC, AlexejPenner approved these changes
LGTM

2022-06-14 07:10 UTC, strickvl requested changes

2022-06-14 07:10 UTC, strickvl commented on examples/github_actions_orchestration/README.md
> +Running your first pipeline using the ZenML GitHubActions orchestrator will create a [GitHub package](https://github.com/features/packages) called **zenml-github-actions** which by default won't be a
```suggestion
Running your first pipeline using the ZenML GitHub Actions orchestrator will create a [GitHub package](https://github.com/features/packages) called **zenml-github-actions** which by default won't be accessible by GitHub Actions.
```

2022-06-14 07:11 UTC, strickvl approved these changes

2022-06-14 07:11 UTC, merged