[WIP] Feat/add nested mlflow
zenml-io/zenml pull request #742
Opened 2022-06-29 16:27 UTC by Val3nt-ML

## Describe changes
We add a parameter `nested` to enable_mlflow decorator to create nested run for each step of a Zen-ML pipeline in MLFlow.

_Example_:
Here is the syntax to use it : 
```python
@enable_mlflow(nested=True)
@step(enable_cache=True)
def my_func(df: pd.DataFrame) -> Output(output_df=pd.DataFrame):
    outpuf_df = my_process(df)
    mlflow.log_param("my_param", 42)
    return output_df
```

And here is the render in MlFlow :
![image](https://user-images.githubusercontent.com/58519204/176487326-04228932-00e3-4287-ba83-23a57d15e7e2.png)

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to docs, I have updated the documentation accordingly.
- [x] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/features/integrations) table.
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-06-29 17:11 UTC, htahir1 commented
@Val3nt-ML  Thank you for the great contribution! We'll leave reviews soon but would be great if you could sign the CLA as indicated by the bot above :-)

2022-06-30 07:52 UTC, Val3nt-ML commented
Hello Hamza,
I will fix it :)

Kind regards
Valentin LAURENT

________________________________
De : Hamza Tahir ***@***.***>
Envoyé : Wednesday, June 29, 2022 7:11:44 PM
À : zenml-io/zenml ***@***.***>
Cc : Valentin Laurent ***@***.***>; Mention ***@***.***>
Objet : Re: [zenml-io/zenml] [WIP] Feat/add nested mlflow (PR #742)


@Val3nt-ML<https://github.com/Val3nt-ML> Thank you for the great contribution! We'll leave reviews soon but would be great if you could sign the CLA as indicated by the bot above :-)

—
Reply to this email directly, view it on GitHub<https://github.com/zenml-io/zenml/pull/742#issuecomment-1170253483>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AN6O5JE6HY4HJBCMHIRSIETVRR7VBANCNFSM52GLZFIQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-30 09:13 UTC, htahir1 commented
Thank you! Im also a bit unsure about this nesting from a user perspective. So if I set nesting as `true` then what happens? Does every `log_param` call make a new run? What are the benefits from a user perspective? We should add these to the docs/examples somewhere (Perhaps in the mlflow_tracking example?)

2022-06-30 09:41 UTC, lopezco commented
> Thank you! Im also a bit unsure about this nesting from a user perspective. So if I set nesting as `true` then what happens? Does every `log_param` call make a new run? What are the benefits from a user perspective? We should add these to the docs/examples somewhere (Perhaps in the mlflow_tracking example?)

If `nested=True` all the mlflow log functions inside the step will log to the nested run. In contrast, if  `nested=False`, the logs will go to the main active run.

2022-06-30 10:00 UTC, lopezco commented
@htahir1 the benefits will be that you can log different metrics or parameters on some steps in separated runs that will be nested into the main pipeline run. 

An example on how we are currently using this is to track the parameters used in some steps and how many rows we are dropping in the filter steps as a metric

2022-06-30 12:16 UTC, htahir1 commented
@lopezco Thank you so much for the clarification. Super useful feature! I think we might need some visibility on this. I can see two places where it would be awesome to add in this PR:

- Updating our [example for mlflow tracking](https://github.com/zenml-io/zenml/tree/main/examples/mlflow_tracking) to reflect this. Perhaps we can add a `nested` section at the bottom with a seperate note explaining that behavior.
- Adding this in the actual code in the docstring of the decorator

WDYT?

2022-06-30 14:52 UTC, lopezco commented on src/zenml/integrations/mlflow/mlflow_step_decorator.py
> +    nested: Optional[bool] = False
In the docstrings or in the example folder?

2022-06-30 16:12 UTC, lopezco commented on src/zenml/integrations/mlflow/mlflow_step_decorator.py
> +        nested: Enable to have nested run during mlflow logging
What do you think about the new docstring including an example?

2022-07-01 12:54 UTC, htahir1 commented
Thank you! Looks really good. I just see some small problems now with linting and formatting. Would you be so kind as to run the following scripts to ensure coding guideliens are met?

```
poetry run bash scripts/format.sh
poetry run bash scripts/lint.sh
poetry run bash scripts/check-spelling.sh
```

This should take care of the issue as it seems to just be superfluous or missing whitespaces.

2022-07-07 09:53 UTC, schustmi requested changes
Just two small comments on type annotations, otherwise looks great!

2022-07-12 08:44 UTC, schustmi approved these changes
LGTM!

2022-07-12 11:41 UTC, htahir1 commented
Awesome, I will merge this now after the tests pass. Thank you so much for the contribution to the folks at Riverbank!

2022-07-12 15:57 UTC, merged