Update readme with latest info from docs page
zenml-io/zenml pull request #810
Opened 2022-07-28 12:04 UTC by dnth

## Describe changes
I updated the README with new info from updated docs.

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/advanced-guide/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Other (add details above)

2022-07-29 12:17 UTC, fa9r requested changes
Really great job, feels much more clear and much more approachable now, love it! 👏 👏 👏 

The only big request I have is to rework or remove the code example. IMO the README is not the right place for this. I would recommend to link to some actual example (quickstart / zenbytes 1 / ...) instead. If you wanted to highlight specific things with the example, e.g., the `@step()` and `@pipeline` syntax, then I would suggest to demonstrate that with short pseudo-code instead. 

My other comments are just minor suggestions, will also approve if those are not changed.

Really looking forward to get this PR in, let me know once it's ready for re-review 😊

2022-07-29 12:17 UTC, fa9r commented on README.md
> +repository of ZenML. Check it out [here](https://github.com/zenml-io/zenfiles).
Would remove that sentence, IMO it's not quite true, ZenFiles is the least-well-maintained code we have I think 😅 

```suggestion
Check out ZenFiles [here](https://github.com/zenml-io/zenfiles)!
```

2022-07-29 12:17 UTC, fa9r commented on README.md
>  First point of call should be [our Slack group](https://zenml.io/slack-invite/).
I think you should also mention creating a GitHub issue as an alternative here

2022-07-29 12:17 UTC, fa9r commented on README.md
> +[API Guide]: https://docs.zenml.io/v/docs/developer-guide/steps-and-pipelines/functional-vs-class-based-api
I think this one should not be here, it's not such a important concept IMO

2022-07-29 14:00 UTC, strickvl reviewed
Some small comments / nits on this. Otherwise I agree that I think it's time to reevaluate what we do with the code example in the README.

2022-08-04 13:59 UTC, fa9r approved these changes
Nice, looks great! I left a few more minor suggestions, but I think you could merge as is. Well done 👍

2022-08-04 13:59 UTC, fa9r commented on README.md
> +Every week, part of the ZenML [core team](https://zenml.io/company#CompanyTeam) will pop in for 30 minutes to interact directly with the community. Sometimes we'll be presenting a feature. Other time
```suggestion
Every week, part of the ZenML [core team](https://zenml.io/company#CompanyTeam) will pop in for 30 minutes to interact directly with the community. Sometimes we'll be presenting a feature. Other times we just take questions and have fun. Join us if you are curious about ZenML, or just want to talk shop about MLOps.
```

2022-08-04 13:59 UTC, fa9r commented on README.md
> +Or if you prefer, [open an issue](https://github.com/zenml-io/zenml/issues/new/choose) on our GitHub repo.
```suggestion
Or, if you prefer, [open an issue](https://github.com/zenml-io/zenml/issues/new/choose) on our GitHub repo.
```

2022-08-04 13:59 UTC, fa9r commented on README.md
> +You can quickly share your stack with anyone with ZenML by exporting them with:
The concept of "stack" has not been introduced yet, maybe you can add a short intro.

```suggestion
In ZenML, a Stack represents a set of configurations for your MLOps tools and infrastructure. You can quickly share your ZenML stack with anyone by exporting the stack:
```

2022-08-04 13:59 UTC, fa9r commented on README.md
>  - Start a thread in our [Slack channel](https://zenml.io/slack-invite).
Maybe also mention "create github issue" here? @strickvl or is that even a recommended way of requesting features? I remember we discussed at some point whether all feature requests should go over the roadmap instead, what was the decision on this again?

2022-08-05 01:10 UTC, merged