Stack recipe CLI improvements
zenml-io/zenml pull request #872
Opened 2022-09-01 14:26 UTC by wjayesh

## Describe changes
Some improvements to the CLI:
- fix "string indices must be integers" bug
- A warning is displayed on pull that overwriting will delete all tfstate files.
- The code now checks for kubectl, helm and docker installation in addition to terraform.
- There's now an option to skip checking `locals.tf` file when you run the `deploy` function.
- `zenml` version in the generated YAML file now automatically reflects the current `zenml` version.

## Pre-requisites
Please ensure you have done the following:
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] If my change requires a change to docs, I have updated the documentation accordingly.
- [ ] If I have added an integration, I have updated the [integrations](https://docs.zenml.io/mlops-stacks/integrations) table and the [corresponding website section](https://zenml.io/integrations).
- [ ] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (add details above)

2022-09-05 15:06 UTC, htahir1 commented
@wjayesh why have you not tagged people here so they know to review? :-)

2022-09-05 15:15 UTC, htahir1 requested changes
Nice, small changes only

2022-09-05 15:15 UTC, htahir1 commented on src/zenml/cli/stack_recipes.py
> +                "docker is not installed on your machine or not available on  "
```suggestion
                "Docker is not installed on your machine or not available on  "
```

2022-09-05 15:15 UTC, htahir1 commented on src/zenml/cli/stack_recipes.py
> +                "helm is not installed on your machine or not available on  "
```suggestion
                "Helm is not installed on your machine or not available on  "
```

2022-09-06 07:33 UTC, strickvl approved these changes
Just a couple of minor things, but otherwise looks good to me.

2022-09-06 07:33 UTC, strickvl commented on src/zenml/cli/stack_recipes.py
> +            RuntimeError: if any tool is not installed.
```suggestion
            RuntimeError: if any required tool is not installed.
```

2022-09-06 07:33 UTC, strickvl commented on src/zenml/cli/stack_recipes.py
> +            force: Force pull the stack recipe overwriting any existing files.
```suggestion
            force: Force pull the stack recipe, overwriting any existing files.
```

2022-09-08 10:08 UTC, schustmi approved these changes
Looks good! Just an optional suggestion to remove a few lines of code, but feel free to ignore. The linting issues and installation issues on windows 3.7/3.8 should be gone once you merge the current develop branch into yours

2022-09-08 10:08 UTC, schustmi commented on src/zenml/cli/stack_recipes.py
> +    def _is_kubectl_installed(self) -> bool:
I think your solution works perfectly fine, I'll just suggest an alternative here that might save some code: You can use `shutil.which("command")` to check if a command exists without actually running it.
```python
def command_available(command: str) -> bool:
    return shutil.which(command) is not None
    
def check_installation(self):
    if not self.command_available("kubectl"):
        raise ...
```

2022-09-09 08:21 UTC, merged